### ISSUE TITLE
Can halotools be installed as root?

### ISSUE THREAD

**Issue by Firestar-Reimu** [astropy/halotools#1060]
I use Archlinux and I want to pack halotools as an [AUR](aur.archlinux.org) package, which will be installed into `/usr/lib/python3.11/site-packages/`

but halotools use pip to install, and pip will say:

```
Defaulting to user installation because normal site-packages is not writeable
```

**Comment by aphearin** [comment]
When I'm installing onto a cluster I always write to a path within my own user domain to avoid permissions problems. Are you able to specify the path where you install? You might also try installing from source, although that will require cython to be installed (and the build time takes several minutes).
