### ISSUE TITLE
Compatibility with Python 3.12

### ISSUE THREAD

**Issue by johannesulf** [astropy/halotools#1073]
Python 3.12 has been released recently. I believe `halotools` is currently incompatible with Python 3.12. That's because the build system requires `cython==0.29.32` which has an incompatibility with 3.12 (https://github.com/cython/cython/issues/5238). Upgrading `cython` to version 3.0.0 or later would probably solve this issue. But I don't know if that would create other problems.

**Comment by aphearin** [comment]
This _should_ be resolved now that #1075 has been merged in. But we might should leave this open until we have a confirmation that the soon-to-be-released `v0.8.3` does indeed work in a 3.12 environment.

**Comment by johannesulf** [comment]
Yes, I can confirm that everything seems to work in python 3.12.

**Comment by aphearin** [comment]
Hey thanks for confirming @johannesulf! The CI testing workflow passes in 3.12, but for reasons I don't understand the [wheels.yml workflow](https://github.com/astropy/halotools/blob/1df4e02d620dd27e22d049d541f09338f007e6f3/.github/workflows/wheels.yml) doesn't seem to generate wheels for 3.12 and so your independent confirmation is reassuring.
