### ISSUE TITLE
Bug in s,mu tpcf clustering function

### ISSUE THREAD

**Issue by duncandc** [astropy/halotools#112]
The analytical randoms are not calculated correctly in clustering.s_mu_tpcf.

I believe the problem is with the volume calculation.

**Comment by aphearin** [comment]
Do you want me to track this down? If so, using the button on the right "assign" me the task, otherwise "assign" yourself.

**Comment by duncandc** [comment]
solved.  this will be fixed in my next pull request.

**Comment by aphearin** [comment]
Fantastic timing.
