### ISSUE TITLE
utility function idea

### ISSUE THREAD

**Issue by duncandc** [astropy/halotools#115]
I think an is_monotonic() function would be useful.  What do you think @aphearin ?

**Comment by aphearin** [comment]
Sure thing. I think this should do the trick, no?

d = np.diff(x)
np.any(d > 0)

**Comment by duncandc** [comment]
I think:

d = np.diff(x)
np.any(d < 0)

**Comment by duncandc** [comment]
maybe we should have a flag for increasing=True

**Comment by aphearin** [comment]
Ask and ye shall receive, @duncandc - see #116
