### ISSUE TITLE
ReadTheDocs build failure due to h5py

### ISSUE THREAD

**Issue by aphearin** [astropy/halotools#154]
RTD fails to build because of the following problem:

In file included from /tmp/pip-build-7QvtZH/h5py/h5py/defs.c:279:0:
    /tmp/pip-build-7QvtZH/h5py/h5py/api_compat.h:27:18: fatal error: hdf5.h: No such file or directory
     #include "hdf5.h"
                      ^
    compilation terminated.

The complete RTD traceback appears below. The only solution for this has been to simply remove h5py from the install requirements and list it as an optional dependency. However, Halotools makes essential use of h5py, so I'd *really* like to avoid this. 

cc @eteq 

You are using pip version 7.1.0, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
DEPRECATION: --download-cache has been deprecated and will be removed in the future. Pip now automatically uses and configures its cache.
Requirement already satisfied (use --upgrade to upgrade): numpy in /usr/lib/python2.7/dist-packages (from -r docs/rtd-pip-requirements (line 1))
Requirement already satisfied (use --upgrade to upgrade): matplotlib in /usr/lib/pymodules/python2.7 (from -r docs/rtd-pip-requirements (line 2))
Requirement already satisfied (use --upgrade to upgrade): Cython in /home/docs/checkouts/readthedocs.org/user_builds/halotools/envs/master/lib/python2.7/site-packages (from -r docs/rtd-pip-requirements (line 3))
Requirement already satisfied (use --upgrade to upgrade): astropy-helpers in /home/docs/checkouts/readthedocs.org/user_builds/halotools/envs/master/lib/python2.7/site-packages (from -r docs/rtd-pip-requirements (line 4))
Requirement already satisfied (use --upgrade to upgrade): astropy in /home/docs/checkouts/readthedocs.org/user_builds/halotools/envs/master/lib/python2.7/site-packages (from -r docs/rtd-pip-requirements (line 5))
Requirement already satisfied (use --upgrade to upgrade): scipy in /usr/lib/python2.7/dist-packages (from -r docs/rtd-pip-requirements (line 6))
Collecting h5py (from -r docs/rtd-pip-requirements (line 7))
  Using cached h5py-2.5.0.tar.gz
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in /usr/lib/python2.7/dist-packages (from matplotlib->-r docs/rtd-pip-requirements (line 2))
Requirement already satisfied (use --upgrade to upgrade): tornado in /home/docs/checkouts/readthedocs.org/user_builds/halotools/envs/master/lib/python2.7/site-packages (from matplotlib->-r docs/rtd-pip-requirements (line 2))
Requirement already satisfied (use --upgrade to upgrade): pyparsing>=1.5.6 in /usr/lib/python2.7/dist-packages (from matplotlib->-r docs/rtd-pip-requirements (line 2))
Collecting nose (from matplotlib->-r docs/rtd-pip-requirements (line 2))
  Using cached nose-1.3.7-py2-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): six in /home/docs/checkouts/readthedocs.org/user_builds/halotools/envs/master/lib/python2.7/site-packages (from h5py->-r docs/rtd-pip-requirements (line 7))
Requirement already satisfied (use --upgrade to upgrade): certifi in /home/docs/checkouts/readthedocs.org/user_builds/halotools/envs/master/lib/python2.7/site-packages (from tornado->matplotlib->-r docs/rtd-pip-requirements (line 2))
Requirement already satisfied (use --upgrade to upgrade): backports.ssl-match-hostname in /home/docs/checkouts/readthedocs.org/user_builds/halotools/envs/master/lib/python2.7/site-packages (from tornado->matplotlib->-r docs/rtd-pip-requirements (line 2))
Building wheels for collected packages: h5py
  Running setup.py bdist_wheel for h5py
  Complete output from command /home/docs/checkouts/readthedocs.org/user_builds/halotools/envs/master/bin/python -c "import setuptools;__file__='/tmp/pip-build-7QvtZH/h5py/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpk6OHQdpip-wheel-:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/h5py
  copying h5py/ipy_completer.py -> build/lib.linux-x86_64-2.7/h5py
  copying h5py/highlevel.py -> build/lib.linux-x86_64-2.7/h5py
  copying h5py/version.py -> build/lib.linux-x86_64-2.7/h5py
  copying h5py/__init__.py -> build/lib.linux-x86_64-2.7/h5py
  creating build/lib.linux-x86_64-2.7/h5py/_hl
  copying h5py/_hl/files.py -> build/lib.linux-x86_64-2.7/h5py/_hl
  copying h5py/_hl/selections2.py -> build/lib.linux-x86_64-2.7/h5py/_hl
  copying h5py/_hl/datatype.py -> build/lib.linux-x86_64-2.7/h5py/_hl
  copying h5py/_hl/dataset.py -> build/lib.linux-x86_64-2.7/h5py/_hl
  copying h5py/_hl/attrs.py -> build/lib.linux-x86_64-2.7/h5py/_hl
  copying h5py/_hl/group.py -> build/lib.linux-x86_64-2.7/h5py/_hl
  copying h5py/_hl/selections.py -> build/lib.linux-x86_64-2.7/h5py/_hl
  copying h5py/_hl/filters.py -> build/lib.linux-x86_64-2.7/h5py/_hl
  copying h5py/_hl/__init__.py -> build/lib.linux-x86_64-2.7/h5py/_hl
  copying h5py/_hl/base.py -> build/lib.linux-x86_64-2.7/h5py/_hl
  copying h5py/_hl/dims.py -> build/lib.linux-x86_64-2.7/h5py/_hl
  creating build/lib.linux-x86_64-2.7/h5py/tests
  copying h5py/tests/common.py -> build/lib.linux-x86_64-2.7/h5py/tests
  copying h5py/tests/__init__.py -> build/lib.linux-x86_64-2.7/h5py/tests
  creating build/lib.linux-x86_64-2.7/h5py/tests/old
  copying h5py/tests/old/test_selections.py -> build/lib.linux-x86_64-2.7/h5py/tests/old
  copying h5py/tests/old/test_dataset.py -> build/lib.linux-x86_64-2.7/h5py/tests/old
  copying h5py/tests/old/test_attrs.py -> build/lib.linux-x86_64-2.7/h5py/tests/old
  copying h5py/tests/old/test_h5t.py -> build/lib.linux-x86_64-2.7/h5py/tests/old
  copying h5py/tests/old/test_h5p.py -> build/lib.linux-x86_64-2.7/h5py/tests/old
  copying h5py/tests/old/test_base.py -> build/lib.linux-x86_64-2.7/h5py/tests/old
  copying h5py/tests/old/test_dimension_scales.py -> build/lib.linux-x86_64-2.7/h5py/tests/old
  copying h5py/tests/old/common.py -> build/lib.linux-x86_64-2.7/h5py/tests/old
  copying h5py/tests/old/test_file.py -> build/lib.linux-x86_64-2.7/h5py/tests/old
  copying h5py/tests/old/test_objects.py -> build/lib.linux-x86_64-2.7/h5py/tests/old
  copying h5py/tests/old/test_attrs_data.py -> build/lib.linux-x86_64-2.7/h5py/tests/old
  copying h5py/tests/old/test_datatype.py -> build/lib.linux-x86_64-2.7/h5py/tests/old
  copying h5py/tests/old/test_group.py -> build/lib.linux-x86_64-2.7/h5py/tests/old
  copying h5py/tests/old/__init__.py -> build/lib.linux-x86_64-2.7/h5py/tests/old
  copying h5py/tests/old/test_h5.py -> build/lib.linux-x86_64-2.7/h5py/tests/old
  copying h5py/tests/old/test_h5f.py -> build/lib.linux-x86_64-2.7/h5py/tests/old
  copying h5py/tests/old/test_slicing.py -> build/lib.linux-x86_64-2.7/h5py/tests/old
  creating build/lib.linux-x86_64-2.7/h5py/tests/hl
  copying h5py/tests/hl/test_dataset_swmr.py -> build/lib.linux-x86_64-2.7/h5py/tests/hl
  copying h5py/tests/hl/test_attribute_create.py -> build/lib.linux-x86_64-2.7/h5py/tests/hl
  copying h5py/tests/hl/test_dims_dimensionproxy.py -> build/lib.linux-x86_64-2.7/h5py/tests/hl
  copying h5py/tests/hl/test_file.py -> build/lib.linux-x86_64-2.7/h5py/tests/hl
  copying h5py/tests/hl/test_dataset_getitem.py -> build/lib.linux-x86_64-2.7/h5py/tests/hl
  copying h5py/tests/hl/__init__.py -> build/lib.linux-x86_64-2.7/h5py/tests/hl
  running build_ext
  Autodetection skipped [libhdf5.so: cannot open shared object file: No such file or directory]
  ********************************************************************************
                         Summary of the h5py configuration
  
      Path to HDF5: None
      HDF5 Version: '1.8.4'
       MPI Enabled: False
  Rebuild Required: False
  
  ********************************************************************************
  Executing api_gen rebuild of defs
  Executing cythonize()
  Compiling /tmp/pip-build-7QvtZH/h5py/h5py/defs.pyx because it changed.
  Compiling /tmp/pip-build-7QvtZH/h5py/h5py/_errors.pyx because it changed.
  Compiling /tmp/pip-build-7QvtZH/h5py/h5py/_objects.pyx because it changed.
  Compiling /tmp/pip-build-7QvtZH/h5py/h5py/_proxy.pyx because it changed.
  Compiling /tmp/pip-build-7QvtZH/h5py/h5py/h5fd.pyx because it changed.
  Compiling /tmp/pip-build-7QvtZH/h5py/h5py/h5z.pyx because it changed.
  Compiling /tmp/pip-build-7QvtZH/h5py/h5py/h5.pyx because it changed.
  Compiling /tmp/pip-build-7QvtZH/h5py/h5py/h5i.pyx because it changed.
  Compiling /tmp/pip-build-7QvtZH/h5py/h5py/h5r.pyx because it changed.
  Compiling /tmp/pip-build-7QvtZH/h5py/h5py/utils.pyx because it changed.
  Compiling /tmp/pip-build-7QvtZH/h5py/h5py/_conv.pyx because it changed.
  Compiling /tmp/pip-build-7QvtZH/h5py/h5py/h5t.pyx because it changed.
  Compiling /tmp/pip-build-7QvtZH/h5py/h5py/h5s.pyx because it changed.
  Compiling /tmp/pip-build-7QvtZH/h5py/h5py/h5p.pyx because it changed.
  Compiling /tmp/pip-build-7QvtZH/h5py/h5py/h5d.pyx because it changed.
  Compiling /tmp/pip-build-7QvtZH/h5py/h5py/h5a.pyx because it changed.
  Compiling /tmp/pip-build-7QvtZH/h5py/h5py/h5f.pyx because it changed.
  Compiling /tmp/pip-build-7QvtZH/h5py/h5py/h5g.pyx because it changed.
  Compiling /tmp/pip-build-7QvtZH/h5py/h5py/h5l.pyx because it changed.
  Compiling /tmp/pip-build-7QvtZH/h5py/h5py/h5o.pyx because it changed.
  Compiling /tmp/pip-build-7QvtZH/h5py/h5py/h5ds.pyx because it changed.
  Compiling /tmp/pip-build-7QvtZH/h5py/h5py/h5ac.pyx because it changed.
  [ 1/22] Cythonizing /tmp/pip-build-7QvtZH/h5py/h5py/_conv.pyx
  [ 2/22] Cythonizing /tmp/pip-build-7QvtZH/h5py/h5py/_errors.pyx
  [ 3/22] Cythonizing /tmp/pip-build-7QvtZH/h5py/h5py/_objects.pyx
  [ 4/22] Cythonizing /tmp/pip-build-7QvtZH/h5py/h5py/_proxy.pyx
  [ 5/22] Cythonizing /tmp/pip-build-7QvtZH/h5py/h5py/defs.pyx
  [ 6/22] Cythonizing /tmp/pip-build-7QvtZH/h5py/h5py/h5.pyx
  [ 7/22] Cythonizing /tmp/pip-build-7QvtZH/h5py/h5py/h5a.pyx
  [ 8/22] Cythonizing /tmp/pip-build-7QvtZH/h5py/h5py/h5ac.pyx
  [ 9/22] Cythonizing /tmp/pip-build-7QvtZH/h5py/h5py/h5d.pyx
  [10/22] Cythonizing /tmp/pip-build-7QvtZH/h5py/h5py/h5ds.pyx
  [11/22] Cythonizing /tmp/pip-build-7QvtZH/h5py/h5py/h5f.pyx
  [12/22] Cythonizing /tmp/pip-build-7QvtZH/h5py/h5py/h5fd.pyx
  [13/22] Cythonizing /tmp/pip-build-7QvtZH/h5py/h5py/h5g.pyx
  [14/22] Cythonizing /tmp/pip-build-7QvtZH/h5py/h5py/h5i.pyx
  [15/22] Cythonizing /tmp/pip-build-7QvtZH/h5py/h5py/h5l.pyx
  [16/22] Cythonizing /tmp/pip-build-7QvtZH/h5py/h5py/h5o.pyx
  [17/22] Cythonizing /tmp/pip-build-7QvtZH/h5py/h5py/h5p.pyx
  [18/22] Cythonizing /tmp/pip-build-7QvtZH/h5py/h5py/h5r.pyx
  [19/22] Cythonizing /tmp/pip-build-7QvtZH/h5py/h5py/h5s.pyx
  [20/22] Cythonizing /tmp/pip-build-7QvtZH/h5py/h5py/h5t.pyx
  [21/22] Cythonizing /tmp/pip-build-7QvtZH/h5py/h5py/h5z.pyx
  [22/22] Cythonizing /tmp/pip-build-7QvtZH/h5py/h5py/utils.pyx
  building 'h5py.defs' extension
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/tmp
  creating build/temp.linux-x86_64-2.7/tmp/pip-build-7QvtZH
  creating build/temp.linux-x86_64-2.7/tmp/pip-build-7QvtZH/h5py
  creating build/temp.linux-x86_64-2.7/tmp/pip-build-7QvtZH/h5py/h5py
  x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DH5_USE_16_API -I/tmp/pip-build-7QvtZH/h5py/lzf -I/opt/local/include -I/usr/local/include -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c /tmp/pip-build-7QvtZH/h5py/h5py/defs.c -o build/temp.linux-x86_64-2.7/tmp/pip-build-7QvtZH/h5py/h5py/defs.o
  In file included from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1761:0,
                   from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:17,
                   from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                   from /tmp/pip-build-7QvtZH/h5py/h5py/api_compat.h:26,
                   from /tmp/pip-build-7QvtZH/h5py/h5py/defs.c:279:
  /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   #warning "Using deprecated NumPy API, disable it by " \
    ^
  In file included from /tmp/pip-build-7QvtZH/h5py/h5py/defs.c:279:0:
  /tmp/pip-build-7QvtZH/h5py/h5py/api_compat.h:27:18: fatal error: hdf5.h: No such file or directory
   #include "hdf5.h"
                    ^
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for h5py
Failed to build h5py
Installing collected packages: h5py, nose
  Running setup.py install for h5py
    Complete output from command /home/docs/checkouts/readthedocs.org/user_builds/halotools/envs/master/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-7QvtZH/h5py/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-W8NJc1-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/docs/checkouts/readthedocs.org/user_builds/halotools/envs/master/include/site/python2.7/h5py:
    running install
    running build
    running build_py
    running build_ext
    Autodetection skipped [libhdf5.so: cannot open shared object file: No such file or directory]
    ********************************************************************************
                           Summary of the h5py configuration
    
        Path to HDF5: None
        HDF5 Version: '1.8.4'
         MPI Enabled: False
    Rebuild Required: False
    
    ********************************************************************************
    Executing cythonize()
    building 'h5py.defs' extension
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DH5_USE_16_API -I/tmp/pip-build-7QvtZH/h5py/lzf -I/opt/local/include -I/usr/local/include -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c /tmp/pip-build-7QvtZH/h5py/h5py/defs.c -o build/temp.linux-x86_64-2.7/tmp/pip-build-7QvtZH/h5py/h5py/defs.o
    In file included from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1761:0,
                     from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:17,
                     from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from /tmp/pip-build-7QvtZH/h5py/h5py/api_compat.h:26,
                     from /tmp/pip-build-7QvtZH/h5py/h5py/defs.c:279:
    /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it by " \
      ^
    In file included from /tmp/pip-build-7QvtZH/h5py/h5py/defs.c:279:0:
    /tmp/pip-build-7QvtZH/h5py/h5py/api_compat.h:27:18: fatal error: hdf5.h: No such file or directory
     #include "hdf5.h"
                      ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------

**Comment by aphearin** [comment]
In light of Andrew Collette's response https://github.com/h5py/h5py/issues/617, I think the temporary solution is just to turn h5py into an optional dependency, and put up some verbose warning messages. Depending on whether RTD has any plans to include HDF5 in their build platform, this solution may need to be sort of permanent, which would be unfortunate since then users would not be able to just "pip install halotools". 

cc @eteq

**Comment by aphearin** [comment]
PR #157 did indeed solve the RTD build problem. Again, this is at the expense of the simplest possible pip install, but is a fine workaround for the time being.

**Comment by aphearin** [comment]
This remains an outstanding nuisance, but #297 and #298 together address this in a way that is at least workable for the time being.

**Comment by stefco** [comment]
@aphearin I have been trying to fix this issue in [my own astro-related project](/stefco/geco_stat) and came across [this official solution](http://read-the-docs.readthedocs.org/en/latest/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules) for generally dealing with hard C dependencies (h5py being a good example).

Since this issue comes up towards the top of Google search results for "h5py readthedocs build failure", I'm posting this link in the hopes that it will save future h5py developers some time.

You can see an example of this in action in [the conf.py file of Dedalus, another science-related python project](https://bitbucket.org/dedalus-project/dedalus/src/5278f1abfe16f578963c4e9ca8ac04c395c3a1f7/docs/conf.py?at=default&fileviewer=file-view-default), which was failing due to the same missing `hdf5.h` header until they fixed it.

Dedalus's usage (wherein they remove `numpy`, `scipy`, `mpi4py`, and `h5py` dependencies):

```python
# Mock modules as per RTF FAQ to avoid hard C dependencies
from unittest.mock import MagicMock

class Mock(MagicMock):
    @classmethod
    def __getattr__(cls, name):
            return Mock()

MOCK_MODULES = ['numpy', 'scipy', 'mpi4py', 'h5py']
sys.modules.update((mod_name, Mock()) for mod_name in MOCK_MODULES)
```

Dedalus also ended up with an [empty requirements.rtd.txt file](https://bitbucket.org/dedalus-project/dedalus/src/5278f1abfe16f578963c4e9ca8ac04c395c3a1f7/docs/requirements.rtd.txt?at=default&fileviewer=file-view-default).

I note that halotools is currently using a separate RTD requirements file, but not using the `mock` approach; I assume this turned out to be effective for your project?

**Comment by aphearin** [comment]
Many thanks for pointing me to this solution, @stefco . My workaround for this problem is clunky and I'll try and implement your fix before the first release of Halotools.
