### ISSUE TITLE
Include incomplete gamma function

### ISSUE THREAD

**Issue by aphearin** [astropy/halotools#160]
In order to make mocks based on the CLF, it is necessary to include an incomplete gamma function into the repo. There is a routine for this in scipy:

http://docs.scipy.org/doc/scipy/reference/generated/scipy.special.gammainc.html#scipy.special.gammainc

However, the a > 0 requirement is too restrictive for the needs of mock-making. Fortunately, @vdbosch69 has a Fortran routine for doing this. Frank - would you be willing to provide standalone fortran code to compute this function?

I have not myself written a f2py wrapper before. @eteq - have you done this? I now know how to do integrate C-wrapped function into the package-template framework, but have not done this with Fortran. How different is the rigamarole? Any chance you could help out with this, Erik? Or short of that, point me to a place in astropy where I can see a simple example?

**Comment by aphearin** [comment]
Actually, @vdbosch69, how complex is your fortran function for this? If it's hundreds of lines of heavily optimized code, I'd rather just wrap it. But another option would be for me to just rewrite it in cython. And/or I could just write the a <= 0 portion in cython, and call the existing scipy function for the a >0 case.

**Comment by vdbosch69** [comment]
Let’s meet briefly today around 1pm (after pizza) to look into the best option.

====================================================================
Prof. Frank C. van den Bosch                                    e-mail: frank.vandenbosch@yale.edu
Astronomy Department, Yale University                                        phone: +1-203-432-0196
P.O.Box 208101                                                                                  fax: +1-203-432-5048
New Haven, CT 06520-8101                                  http://www.astronomy.yale.edu/vdbosch
====================================================================

**Comment by surhudm** [comment]
It is actually not that complicated. I was going to suggest the same thing!

Otherwise you can use the recurrence relations, see:

https://en.wikipedia.org/wiki/Incomplete_gamma_function#Properties

Cheers,
Surhud

**Comment by aphearin** [comment]
Thanks for the tip, @surhudm ! Probably I’ll just write it myself then. I prefer to have code natively in python whenever possible.
