### ISSUE TITLE
improve transparency of simulation download script

### ISSUE THREAD

**Issue by aphearin** [astropy/halotools#165]
As suggested by @parejkoj, the download script should notify the user the download directory of the catalog. 

Also, the Getting Started section should have the following usage example that can be used to verify that you did indeed download it and that it's located in the download location:

    halocat = HaloCatalog(simname = 'something', redshift = z)

**Comment by aphearin** [comment]
Put the download location in the "-h" help option

**Comment by parejkoj** [comment]
Actually, scripts/download_initial_halocat.py doesn't even allow -h. You should probably use ArgParse for these...

**Comment by parejkoj** [comment]
Oh god, you're parsing things yourself in download_alternate... Look up ArgParse, be amazed.

**Comment by aphearin** [comment]
This is resolved by #297
