### ISSUE TITLE
obliterate ~50Mb data file from git history

### ISSUE THREAD

**Issue by aphearin** [astropy/halotools#166]
As noticed by @parejkoj

**Comment by eteq** [comment]
The file in question is ``halotools/mock_observables/sinha_pairs/random_AbM_swot_scatter0.10dex_All_V_PEAK_Zspace.ff`` from commif 60cfe7d .  Another similar large file from the same commit is ``halotools/mock_observables/sinha_pairs/cmassmock_AbM_swot_scatter0.10dex_All_V_PEAK_Zspace.ff``.  Both were then remove a few commits later in 802d65e1da5712d196b8a9e495fdcb1712cbc160

**Comment by aphearin** [comment]
As discussed in #282 , this has been resolved through git arcana discovered by @eteq
