### ISSUE TITLE
IndexError in clustering.py

### ISSUE THREAD

**Issue by kilianbreathnach** [astropy/halotools#169]
Error comes from line 134 in halotools/mock_observables/clustering.py

When performing autocorrelation on a dataset with more than 1e6 galaxies, the sample is downsized. The placeholder for sample2 is downsized from the already downsized sample1 using indices from the original sample1. The simple fix is to just replace the code with

sample2 = sample1

or something similar. This will be faster too.

**Comment by duncandc** [comment]
good spot!
