### ISSUE TITLE
Improve interface to tpcf_jackknife

### ISSUE THREAD

**Issue by BenediktDiemer** [astropy/halotools#188]
The tpcf_jackknife interface "feels" quite different from the tpcf function, and has some surprising defaults (box size 250 Mpc etc). The user shouldn't be required to pass randoms but just a number of randoms, and the box size / period parameters should interact somehow.

**Comment by BenediktDiemer** [comment]
Another unexpected behavior is the following: if Nsample > max_sample_size, the function also returns cross-correlations! The reason is that the samples get randomly down-sampled independently, after sample1 = sample2 (if no cross-correlation desired) and np.all(sample1 == sample2) operations thereafter. The latter then gives false and makes the function think that the user has passed two different samples.

I'd get rid of the (sample1 == sample2) checks altogether and replace them with a flag that is evaluated once at the very beginning.

**Comment by duncandc** [comment]
This is great.  keep finding all these little things.  I will fix them in one swoop when Andrew and I update the pair counter next week.

**Comment by duncandc** [comment]
I agree with the randoms issue too.  Although, there should be a random seed keyword argument, so as to make the calculation repeatable.

**Comment by duncandc** [comment]
Both of these issues should be fixed in the next pull request.
