### ISSUE TITLE
Bug in tpcf_jackknife when point exactly on box boundary

### ISSUE THREAD

**Issue by BenediktDiemer** [astropy/halotools#189]
If a point has a coordinate that is exactly Lbox, an error occurs in get_subvolume_labels:

halotools/halotools/mock_observables/clustering.py", line 510, in get_subvolume_labels
    j_index_1 = inds[index_1[:,0],index_1[:,1],index_1[:,2]].astype(int)
IndexError: index 5 is out of bounds for axis 2 with size 5

because the index is Nsub instead of Nsub - 1. One easy fix is to replace Nsub values in the index array with Nsub - 1, e.g.

        for i in range(3):
            index_1[:, i] = np.where(index_1[:, i] == Nsub[i], Nsub[i] - 1, index_1[:, i])

**Comment by duncandc** [comment]
fixed on next pull request.
