### ISSUE TITLE
case use: DeltaSigma when galaxy-matter cross tpcf is negative

### ISSUE THREAD

**Issue by duncandc** [astropy/halotools#216]
It is possible that the galaxy matter cross correlation, xi_gm, takes negative values. 

Currently we integrate the log(xi_gm) when calculating the galaxy-galaxy lensing signal DeltaSigma.  

Right now, we throw an error if xi_gm<0.  Is there something better to do?

**Comment by aphearin** [comment]
1. Integrate in linear space
2. Perform the integral in log-space but do it piece-wise
3. Shift the values to be positive before logarithmic integration, then shift them back. 

@surhudm @vdbosch69 - other suggestions?

**Comment by surhudm** [comment]
Can you point me to the code where this is done? I do not understand why
you are integrating log(xi_gm) at all.

**Comment by vdbosch69** [comment]
haven’t thought about this much, but perhaps you can integrate  1+xi_gm(r) using
logarithmic integration over r, and then subtract the 1+ component (this should work unless you
integrate out to infinity).

F

**Comment by vdbosch69** [comment]
I think he means he is integrating xi_gm but using logarithmic integration intervals in r.
Is that correct AH?

**Comment by aphearin** [comment]
This code is not in the master branch - @duncandc has been developing it in a branch on his fork so we'll have to wait for him to point us to the specific branch. However, now that you point it out I see that I didn't understand this Issue before commenting. I also don't know where taking the log of xi_gm comes into play when computing DS. Let's wait for @duncandc to clarify.

**Comment by surhudm** [comment]
Ok I found the branch then, @duncandc is basically interpolating log(xigm)
vs log(r), and that will pose a problem if you have negative xigm. The
solution is simple, interpolate log(1+xigm) vs log(r), this is exactly what
we do in the codes that @vdbosch69 and I developed and what I mentioned in
my comment on #218.

**Comment by duncandc** [comment]
https://github.com/duncandc/halotools/blob/mock_obs_devel/halotools/mock_observables/delta_sigma.py

**Comment by aphearin** [comment]
Right, so your integrand is a spline of xi(r) and you build the spline in log-log space. Are you sure log-log interpolation is necessary? Do you run into numerical problems if you build the table in log-linear space?

**Comment by aphearin** [comment]
Brief aside: this code is exceptionally clearly written and easy to understand. Really nice work.

**Comment by duncandc** [comment]
I am going to fit log(1+xi).  Any other issues, we can open a new issue thread.

**Comment by manodeep** [comment]
Seems like this issue is different from the one I have seen. Does the tpcf use the binning in dec/ra ?

**Comment by duncandc** [comment]
@manodeep what issue are you referring to?  This uses the real space tpcf function.  binning is done in r.  the pair counter uses cells.

**Comment by manodeep** [comment]
So the inputs positions are (xyz) - rather than ra/dec/cz? For some of Jen's weird correlation functions on mocks, I got negative xi which went away once I removed the binning in my codes. In all of those cases, pimax was effectively infinity..

On a different note, you can improve performance by switching the interpolation from r to r^2, i.e., 

set up the initial interpolation as:
```python
 xi = InterpolatedUnivariateSpline(rbin_centers**2, np.log10(xi+1.0), ext=0)

 def f(pi,rp):
     r2 = rp**2+pi**2
     return mean_rho*(1.0+(10.0**xi(r2)-1.0))
```
and then you can avoid the sqrt inside f().
