### ISSUE TITLE
redshift space / wp tpcf wrong

### ISSUE THREAD

**Issue by duncandc** [astropy/halotools#218]
is returning neagtive values for xi.  not sure the issue.  May be a problem with the pair counter.  This problem also propagates to the w_p function

**Comment by surhudm** [comment]
Negative values for xi can happen. For example, for central central
correlation function, at radii below the typical virial radius, xi equals
-1. So it doesn't necessarily have to be a bug in the pair counter.

You should interpolate log(1+xi) as 1+xi is always positive.

**Comment by aphearin** [comment]
Surhud is correct. Unless you have some other reason to believe that the cfs are wrong, negative values in and of themselves are not an indication of a bug.

**Comment by duncandc** [comment]
sorry, yes, negative values can happen.  The problem was, for some actual calculations, all values were coming out negative.    

I have tracked this down to an issue with the xy_z space pair counter.  creating an new issue.
