### ISSUE TITLE
RSD Multipoles

### ISSUE THREAD

**Issue by aphearin** [astropy/halotools#233]
Include in mock_observables and also as a convenience function wrapped around the mocks

CC @duncandc

**Comment by duncandc** [comment]
the functions to calculate the multipoles are now in mock obs (next pull reuqest).  these take the output of the s_mu_tpcf functions.  convenience functions are left to @aphearin

**Comment by aphearin** [comment]
When you say "convenience functions", do you mean methods bound to composite model instances, or am I to write some functions in addition to those?

**Comment by duncandc** [comment]
methods bound to model instances.  If we want them.  I generally have not been touching those.

**Comment by aphearin** [comment]
Right, sure, I'll take care of that. Just leave this Issue open. I'm assigning it to myself now.
