### ISSUE TITLE
Pairwise velocity dispersion

### ISSUE THREAD

**Issue by aphearin** [astropy/halotools#235]
Include radial and projected PVD. 

CC @duncandc

**Comment by duncandc** [comment]
@aphearin is the projected pairwise velocity distribution a thing?

radial is done.  to be included with next pull request.

**Comment by duncandc** [comment]
yes.  dispersion.  right now i have a function for the mean and the dispersion (radial).

**Comment by aphearin** [comment]
As far as 2D vs 3D goes, here's my opinion on the order of priority:

1. <Vr> vs 3D separation r
2. <Vz> vs 2D separation rp
3. sigma^2(Vz) vs. 2D separation rp
4. sigma^2(Vr) vs. 3D separation r

Now the remaining cases are interesting only for a much more targeted set of questions:
5. sigma^2(Vz) vs. 3D separation r
6. sigma^2(Vr) vs. 2D separation rp
7. <Vr> vs 2D separation rp
8. <Vz> vs 3D separation r

I don't think there are any other cases of interest for now. The first set is vastly more important than the second set. At some point we can add in tangential, but that can be deferred to a future PR. 

@surhudm - if I have forgotten something obvious, please chime in.
