### ISSUE TITLE
nearest neighbor distance

### ISSUE THREAD

**Issue by aphearin** [astropy/halotools#237]
Include in mock_observables a function returning the distance to the nearest neighbor in an unmarked set of points. 

Additionally, should include the nearest distance to a set of points subject to an additional cdef-defined boolean-returning function

CC @duncandc

**Comment by duncandc** [comment]
The unmarked version has been done and will be included my next pull request.  

As it is written, this can be a memory intensive (and slow) calculation.  Searching for the nearest nth neighbor in a Bolshoi like sample out to ~10 Mpc can take ~10(s) of seconds.

The meat of this calculation is done in by pair_counters.pair_matrix calling cpairs.pairwise_distances.  I bet some performance could be squeezed out of those.
