### ISSUE TITLE
VPF/UPF

### ISSUE THREAD

**Issue by aphearin** [astropy/halotools#238]
Create convenience wrapper function for the Void Probability Function and Underdensity Probability Function 

The VPF is defined as the probability that a sphere of radius r contains zero galaxies of a given type. 

The UPF is defined as the probability that a sphere of radius r has a galaxy density less than some fraction of the overall mean density for that galaxy type. 

CC @duncandc

**Comment by duncandc** [comment]
I think this is best accomplished by writing a new pair counter using the basic structure of the cpairs module that counts pairs in radial bins **per object**.  i.e. given 2 samples of length N1 and N2 and Nr radial bins it returns an array of shape (N1, Nr).

**Comment by aphearin** [comment]
That sounds unnecessarily slow due to the memory allocation. I think this calculation is extremely similar to pair counting. Suppose that there are N1 sphere-centers and N2 galaxies. For every sphere with Npts > Npts_thresh, increment the histogram. Npts_thresh = 0 for the VPF; and for the UPF Npts_thresh = U*mean_N2_density*(4pi/3)*rbin**3. Then at the end, when the histogram-updating is done, simply divide the counts by N1.

**Comment by duncandc** [comment]
OK, I have coded something that up which should good.  I am calling it "threshold_npairs".  It will be beautiful.

**Comment by aphearin** [comment]
Cool. At some point we'll want to be able to update the histogram with the output of a marking function in the usual way, but that feature is definitely not a priority.

**Comment by duncandc** [comment]
Right, but as in the other cases, I think that will be a separate function.
