### ISSUE TITLE
isolation criteria

### ISSUE THREAD

**Issue by aphearin** [astropy/halotools#239]
- is there any other point within a given sphere?
- is there any other point within a given cylinder?
- Is there any point passing a boolean criteria (logM1 < logM2 + 0.5) within a given sphere? cylinder? (Riff on Duncan’s wfunc MCF structure)

Very closely related to #238 

CC @duncandc

**Comment by duncandc** [comment]
simple isolation determination is done--to be included in next pull request.  The marked version has yet to be coded up.
