### ISSUE TITLE
create usage tutorial on mock_observables.redshift_space_tpcf()

### ISSUE THREAD

**Issue by duncandc** [astropy/halotools#243]
none currently exists

**Comment by aphearin** [comment]
@duncandc - do you think a usage tutorial is necessary here? Or would having a clearer and more physically motivated docstring be sufficient? I leave it up to your judgement. I will be in charge of resolving #490 before the v0.2 release. If you think that's sufficient, just close this issue. If you think that's not enough, and that a proper IPython Notebook tutorial is required, then leave this issue open and assign me the task.
