### ISSUE TITLE
Move igraph dependencies inside function calls

### ISSUE THREAD

**Issue by aphearin** [astropy/halotools#247]
This way users won't get an error message just by importing the module, which a couple of people have reported as confusing and worrisome. 

Also add igraph to list of optional dependencies on the halotools/docs/install page, being explicit about which igraph to use

CC @duncandc

**Comment by duncandc** [comment]
boolean indicating if igraph is installed is set at the beginning of the script.  An error is raised if this is set to False, and a user tries to use a function which uses the igraph functionality.
