### ISSUE TITLE
split scatter models into constant and variable 

### ISSUE THREAD

**Issue by duncandc** [astropy/halotools#263]
@aphearin 

I think there should be two separate models for constant scatter and variable scatter.  This should make it much more transparent.  They could both be a subclass of a super LogNormalScatterModel or NormalScatterModel.

**Comment by duncandc** [comment]
P.S. developing this in my own fork/branch

https://github.com/duncandc/halotools/tree/sham_devel

**Comment by aphearin** [comment]
This is definitely a good idea. I'm trying to move away from having too many options within a single constructor, and splitting up separate functionality like this into a subclass  is how I'm making the style changes. 

Probably the least amount of work in building the subclass would be if you keep the internals fixed, but just use the interpolation on a single control point. Whatever you do, don't change the param_dict keys. So in your subclass, the instance should have a single parameter called 'scatter_model_param1' (I think I remembered that right).

**Comment by aphearin** [comment]
In light of discussion with @duncandc in #746 , this issue is no longer relevant.
