### ISSUE TITLE
Obliterate all hideous appearances of "haloes" spelling

### ISSUE THREAD

**Issue by aphearin** [astropy/halotools#267]
CC @duncandc - let the spelling war begin.

**Comment by surhudm** [comment]
What do you think of this @vdbosch69? :)

**Comment by vdbosch69** [comment]
I take a seat at the sideline, and patiently await the response from the MNRAS editor
who will insist on the Queens English being used in a Journal that carries the name `Royal’.
This kind of rebellion is typical of newbies; of young, naive man that suffer from hormonal
issues; I act as a mere bystander in this futile attempt to overturn eons of linguistic evolution.



====================================================================
Prof. Frank C. van den Bosch                                    e-mail: frank.vandenbosch@yale.edu
Astronomy Department, Yale University                                        phone: +1-203-432-0196
P.O.Box 208101                                                                                  fax: +1-203-432-5048
New Haven, CT 06520-8101                                  http://www.astronomy.yale.edu/vdbosch
====================================================================

**Comment by surhudm** [comment]
Age turneth thou wise!

**Comment by eteq** [comment]
:+1: to the revolution proposed by @aphearin.  Let the young sweep away the old!

Also, note that [PEP8](http://legacy.python.org/dev/peps/pep-0008/), the official style guide for Python code, has the following to say:
> When writing English, follow Strunk and White.

and Strunk and White is an *American* English style guide. A bit circumstantial as far as evidence goes... but stiil.
