### ISSUE TITLE
Value added halo catalogue columns

### ISSUE THREAD

**Issue by duncandc** [astropy/halotools#287]
There are a few basic quantities which should be added to the halo catalogue/mocks.

host_halo_id
host_halo_mvir

Let's update this as needed.

**Comment by aphearin** [comment]
I think r/Rvir is also pretty basic, no?

**Comment by aphearin** [comment]
Also, @duncandc , for mock catalogs how does *host_halo_id* differ from *halo_upid*?

**Comment by duncandc** [comment]
host_halo_id and halo_upid are the same thing.  The only thing I might change is so that host haloes aren't -1, but instead equal to the halo id.  

Yes, r/r_vir would be nice.

**Comment by surhudm** [comment]
I concur with Duncan's suggestion here. In my analysis of Rockstar halos, I
had to convert the upid from -1 to the halo id many times.

**Comment by aphearin** [comment]
Right. In fact this is already implemented in the existing catalogs for the same reason I'm sure we all have. The halo catalogs supplied by Halotools all have a column 'halo_hostid' which is exactly this conversion. It just is not included in the mocks by default, but existing code already permits you to choose any arbitrary columns in the mocks that you like.

**Comment by aphearin** [comment]
Let's leave this issue open so that I remember to change the default settings, and also to make the 'additional_haloprops' feature more discoverable.
