### ISSUE TITLE
doctests in .rst files are not executed 

### ISSUE THREAD

**Issue by aphearin** [astropy/halotools#308]
python statements embedded in the Halotools documentation are not executed by the test runner, so there no doctests in the .rst files are performed. I am currently moving towards the first official release and writing reams and reams of documentation, so getting this fix implemented soon would be very helpful. 

Simple demonstration of the bug appears here: https://github.com/aphearin/halotools/commit/a3676d08308d30628e9f4b8e2ef3101af017b021

This issue has been ported over from https://github.com/astropy/halotools/issues/296. In that Issue, there were actually two entirely separate problems that got lumped together. The first has been resolved, the present issue remains. 

This problem seems closely connected to https://github.com/astropy/astropy-helpers/issues/143 and https://github.com/astropy/astropy-helpers/pull/184. From reading those issues, it seems likely that what is going on here is that Halotools was originally built from an old version of the package-template, and only some of the changes to the template files got updated.

Tagging @embray since he was in charge of the PRs associated with those issues, and @bsipocz since chimed in on the original  https://github.com/astropy/halotools/issues/296.

**Comment by bsipocz** [comment]
@aphearin - I see similar problems with astroquery https://github.com/astropy/astroquery/issues/633 but didn't have the time yet to investigate it. Anyway, once I got a fix I'll let you know, or port it in a PR for halotools, too.

**Comment by aphearin** [comment]
Thanks, @bsipocz . Just to be sure, I can confirm two things related to comments you made when raising  https://github.com/astropy/astroquery/issues/633:

1. The bug shown here as manifested in Halotools has no apparent connection to --remote-data

2. There is no problem I am aware of with tests in the docstring being run. 

Also, in case this helps track things down, here is a bit more of the phenomenology. When I run the full test suite with `python setup.py test`, in the report there are no `.rst` files in the list of modules for which tests were executed. And when I throw the `-t` flag and pass in a `.rst` file that *does* have a doctest in it, I get the following error:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "halotools/_astropy_init.py", line 111, in test
    coverage=coverage, open_files=open_files, **kwargs)
  File "/Users/aphearin/anaconda/lib/python2.7/site-packages/astropy/tests/helper.py", line 146, in run_tests
    "Can not test .rst files without a docs_path "
ValueError: Can not test .rst files without a docs_path specified.

Let me know if there's anything else I can do to help.

**Comment by bsipocz** [comment]
Thanks, this will be helpful.

**Comment by aphearin** [comment]
@bsipocz - my workaround for this issue just got a lot more laborious due to #367. Have you had a chance to look into this issue yet? Is there anything I can do to help?

**Comment by aphearin** [comment]
This has been resolved (weeks ago) by updating the helpers.
