### ISSUE TITLE
simple TPCF call for mocks

### ISSUE THREAD

**Issue by duncandc** [astropy/halotools#31]
We should create a very simple interface for running a no-frills TPCF on mocks w/ PBCs.

**Comment by aphearin** [comment]
Yes, agreed. I will be working on mock-dev for the next several weeks, but will get to this eventually if you don't beat me to it.

**Comment by aphearin** [comment]
This is done, for both mock objects and model objects (the latter case successively creates multiple mock realizations, and returns the median/mean result from the realizations).
