### ISSUE TITLE
Relax MPI compatibility problem

### ISSUE THREAD

**Issue by aphearin** [astropy/halotools#32]
The way mock_observables is currently written, the test suite automatically fails if the platform does not have MPI installed. But MPI should be optional. The way to handle this is 

* Step 0: Do all development in a virtual environment which does not have MPI installed, so that package-dependency errors such as this are caught from the get-go. 

* Step 1: Follow astropy's try/except-based pattern of implementing a global variable HAS_MPI, and add a py.test decorator marker. This is implemented throughout astropy with HAS_SCIPY, HAS_MATPLOTLIB, etc, so that is the place to look to see how to do it.

@duncandc - can you handle this?

**Comment by duncandc** [comment]
Yeah man.  Super swamped right now.  This has been on my list for a little while...

**Comment by aphearin** [comment]
Not that time-sensitive, obviously, since this is a long-standing bug. Mostly I just wanted to raise an Issue so I know you're aware of it, and will take care of it eventually.

**Comment by aphearin** [comment]
Mock_observables has been wiped clean.
