### ISSUE TITLE
examine abundance function models for sanity...

### ISSUE THREAD

**Issue by duncandc** [astropy/halotools#337]
@eteq, I have created some custom Schechter function models using the astropy.modeling.model tools.  I want to use these for both fitting abundance functions and defining ones from the literature.  

I have code on my fork of halotools on the sham_devel branch.

halotools.empirical_models.abundance_matching.schechter_functions.py 
and 
halotools.empirical_models.abundance_matching.premade_abundance_functions.py

If you or someone else who has worked with models could take a look at these, and see if I follow conventions and use them intelligently, that would be wonderful.   

If you are feeling adventurous, I also coded up a custom fitter:
halotools.empirical_models.abundance_matching.abundance_fitter.py

**Comment by aphearin** [comment]
Closing this issue since there are no longer any plans to include deconvolution abundance matching into halotools.
