### ISSUE TITLE
halotools test --coverage throws travis error

### ISSUE THREAD

**Issue by aphearin** [astropy/halotools#339]
My full test suite for #338  is passing except for the `SETUP_CMD = 'test --coverage'` option. 

@bsipocz or @eteq - have either of you ever seen this before? 

https://travis-ci.org/astropy/halotools/jobs/107009559

=================== 356 passed, 64 skipped in 228.12 seconds ===================
Saving coverage data in .coverage...
Saving HTML coverage report in htmlcov...
The command "python setup.py $SETUP_CMD" exited with 0.
$ if [[ $SETUP_CMD == 'test --coverage' ]]; then coveralls --rcfile='halotools/tests/coveragerc'; fi
Submitting coverage to coveralls.io...
Coverage submitted!
Couldn't find a repository matching this job.
'url'

**Comment by bsipocz** [comment]
@aphearin - We see it for all of the packages, @astrofrog figured out that's it's a problem on out site, so we just need to wait it out.

**Comment by bsipocz** [comment]
@aphearin - I've just restarted a build on this, and it seems to be resolved already.

**Comment by aphearin** [comment]
Many thanks, @bsipocz - the issue appears to be resolved now.
