### ISSUE TITLE
Improve documentation and convenience of angular clustering

### ISSUE THREAD

**Issue by aphearin** [astropy/halotools#376]
The process of generating randoms for the `angular_tpcf` should be made simpler and be better documented. 

@cwhite1026, you should probably wait until we get this in the repo until to do your angular clustering analysis. It would be too laborious for you to figure out how to do this without better documentation. It shouldn't be too much trouble getting this in the repo within a week.

**Comment by duncandc** [comment]
I think we can count this as done.

**Comment by aphearin** [comment]
@cwhite1026 - disregard this notice if you have since moved on, but there is now a step-by-step tutorial demonstrating how to use `angular_tpcf`.
