### ISSUE TITLE
AppVeyor build problem

### ISSUE THREAD

**Issue by aphearin** [astropy/halotools#389]
While attempting to make Halotools windows-compatible, I started to set up AppVeyor CI and ran into trouble. I haven't used AppVeyor before and so I'm not sure whether the problem is a simple configuration issue on my end, or if there is a non-trivial problem in the `astropy_helpers` submodule. I mentioned this to @eteq , who told me that one of @bsipocz, @embray or @astrofrog would be able to point me in the right direction. 

After pointing AppVeyor to astropy/halotools/master, the build initialized but failed almost immediately with the following message:

    Build started
    git clone -q --branch=master https://github.com/astropy/halotools.git C:\projects\halotools
    git checkout -qf d0a4524e5bcf2a6ab38684a2f85aea277612fb1e
    Specify a project or solution file. The directory does not contain a project or solution file.

**Comment by embray** [comment]
You need an appveyor.yml

**Comment by aphearin** [comment]
Right, I noticed that appveyor.yml is present in the astropy_helpers, but I think you are saying I need an independent one?

**Comment by aphearin** [comment]
Yup, looking at the version of that file in the helpers, it's clear that this is helpers-specific, nothing to do with halotools. Ok, thanks.
