### ISSUE TITLE
AbundanceFunction objects are not pickle-able

### ISSUE THREAD

**Issue by duncandc** [astropy/halotools#394]
For an unknown reason, the AbundanceFunction objects can not be pickled.  It would be ideal to be able to pickle them and save so they can be loaded and used to make mocks.  

@aphearin, do know what the problem is?

**Comment by aphearin** [comment]
In what way is a pickled abundance function ideal?

**Comment by duncandc** [comment]
I would like to calculate and fit an abundance function and save the result.  Then multiple codes could load and use the object without hard coding the result in.  Is there a better option?

**Comment by aphearin** [comment]
What is the disadvantage of hard-coding the best-fit parameters into the source code?

**Comment by duncandc** [comment]
If I change how I calculate the abundance function, e.g. bins, cuts, simulations... I don't have to go back and edit a whole bunch of code.  You don't agree?

**Comment by aphearin** [comment]
I just don't understand. If you want to be able to change how you do the calculation, how does pickling the result save you any trouble? A pickled object is about as hard-coded as it gets.

**Comment by aphearin** [comment]
My reaction is that it sounds like you should just be using pickled objects in your own workflow, but not in the global repo

**Comment by duncandc** [comment]
I am imaging I have some code called, calculate_sdss_mstar_abundance.py

Then I have some code called, make_sham_mock.py that uses the output of the previous script.  

Right now I have to run the first script.  Then copy and paste the results into the second script when I initialize the AbundanceFunction.  The run the second script.  It would be nice to be able to run the first followed by the second with not copying and pasting, just automatically loading the result of the first in the second.

**Comment by aphearin** [comment]
So the final result of `calculate_sdss_mstar_abundance.py` is an `AbundanceFunction` instance (or maybe an instance of an `AbundanceFunction` sub-class)?

**Comment by aphearin** [comment]
If so, can't your `make_sham_mock` code just accept an instance as an input argument? Then whatever data is bound to the result of `calculate_sdss_mstar_abundance` will be carried into `make_sham_mock`, with no hard-coding of anything except attribute names, which should be standardized anyway.

**Comment by duncandc** [comment]
hmmmmm im confused.  I think this would be easier in person

**Comment by aphearin** [comment]
Sounds like this might be easier to discuss in person while looking at code. I'll close this issue for now and we can revisit it next week when I get back in town
