### ISSUE TITLE
Bug in the cross correlation function calculation

### ISSUE THREAD

**Issue by aphearin** [astropy/halotools#4]
In observalbles.py:
When computing the cross-correlation function using the function 'TP_estimator' we are accounting for the same normalization factor for the two sets of data points (sample1 and sample2). 
The right calculation should be:
xi_gm = [D1D2/(N1N2)]/[N_rN_rRR]
instead of 
xi_gm = [D1D2/(N1N1)]/[N_rN_rRR]

The best thing to do will be to add factor3 = (len(sample1)0.5)*((len(sample2)0.5))/len(randoms) and to pass this factor to 'TP_estimator' when computing the cross-correlation function.

This bug has to be fixed in both:
1. two_point_correlation_function
2. two_point_correlation_function_jackknife

Shany

**Comment by duncandc** [comment]
This has been fixed.
