### ISSUE TITLE
aggregation module API

### ISSUE THREAD

**Issue by duncandc** [astropy/halotools#43]
I do not understand the proposed API for this module.  The API will depend on the attributes of the mock objects.  Let me sketch out my understanding of the mock strucutre as it relates to this module   

1.) Mocks will have attributes for all the halo and galaxy props.  e.g. mock.mstar will be an array of stellar masses, and mock.halo_id will be an array of halo ID numbers.
2.) For convenience the user can bundle these into astropy tables.  One for galaxies and one for haloes.  These tables will have keyword access, e.g. mock.gal_table['mstar'].
3.) We don't want those tables to be the default because they are too slow to create.

The aggregation API should be able to do aggregation operations on either an astropy table, or mock object directly.  The functions should return the same result in both cases.

Questions:
1.)  what should the functions return?
     a.) an array
     b.) a table with a new column
     c.) a mock with a new attribute
2.) Should we internally bundle the needed mock attributes into a table or rec array?
3.) How should the aggregation functions themselves be structured?  Right now they operate on slices of record arrays.     

Thoughts:
I think the aggregation operations will take time comparable to creating an astropy table (or longer).  It may be over optimization to have them be able to run on anything other than a table.

**Comment by aphearin** [comment]
1. An array. I see no need to save the user a single line of code creating a new table column. 

2. When does this bundling take place?

3. Why do the functions operate on slices? Shouldn't they operate on an entire input array? What functionality requires a slice?

**Comment by duncandc** [comment]
The actual function that calculates a group-wise property.  e.g.

broadcast_cen_ssfr(x):
    mask = (x['cen']==1)
    return x['ssfr'][mask]

currently x is a slice of a galaxy table corresponding to one group.

**Comment by aphearin** [comment]
I don't understand why x *must* be a slice. At what point is this assumption used? If you pass this function the entire galaxy table, sure, it would be buggy, but we would never do that. It would return the correct result provided that it is only ever passed a single group, right?

**Comment by duncandc** [comment]
O the function doesnt care.  The code that passes x to the aggregation function slices the array by groups.  Im not so worried about the slicing.  I am thinking about what to do when we no longer have a table-like object to work with.

**Comment by aphearin** [comment]
Ahh, ok, yes, now I see the problem. It's not clear how to broadcast for the case of a straight numpy array. Let me think on it.

**Comment by aphearin** [comment]
Actually, for this particular function, where a single property is broadcast, couldn't we just require that the user supply the boolean mask? This way, it could be one of two options:

* Table case: mask = (x['cen']==1)
* Array case: mask = (x.iscen==1)

**Comment by aphearin** [comment]
So, the user would supply a funcobj that returns a mask, and the user could supply either a Table or an array of SSFR. Make sense?

**Comment by duncandc** [comment]
That makes sense... but that is only one calcualtion.  What about other calculations?

**Comment by aphearin** [comment]
More productive to take it on a case-by-base basis. What other calculations does the above idea not translate to?

**Comment by duncandc** [comment]
any function that operates on more than 1 value.  e.g. distance from host halo center.

def r_host(x):
     central = (x['upid']==-1)
     xcen = x['x'][central]
     ycen = x['y'][central]
     zcen = x['z'][central]
     r = np.sqrt((x['x']-xcen)**2+(x['y']-ycen)**2+(x['z']-zcen)**2)
     return r

Now we would need to pass in 3 arrays and a mask...

**Comment by aphearin** [comment]
So what? Just use the *args syntax. That way, the user can pass in whatever number of arguments their aggregation function requires. What is the problem?
