### ISSUE TITLE
Startup helper scripts should allow the user to store cats in alternate locations

### ISSUE THREAD

**Issue by mclaughlin6464** [astropy/halotools#456]
I recognize that the ability to store cats in alternate locations has recently been included. However, the scripts download_initial_halocat.py and download_additional_halocat.py just put the new catalogs into the cache location. There are scenarios (like mine) where I have a very small disk quota and cannot store any cats locally, which made setting up an initial cache difficult. Adding a new argument to the above scripts and passing the input into the download_dirname kwarg in the dowman calls was simple enough to do.

**Comment by aphearin** [comment]
Good point, @mclaughlin6464 , I added this feature to the DownloadManager, but forgot to add it to the download script. So if you were managing your downloads using the sim_manager package, this is no problem, but it's not currently an available argument in the convenience scripts. 

I'm not sure I understood you correctly though - did you yourself just modify the scripts for this purpose? If so, would you mind putting in a pull request with the modified scripts?

**Comment by mclaughlin6464** [comment]
I did make modifications to my own scripts, and I just made a pull request for them. I've tested them and they work on my system.

**Comment by aphearin** [comment]
I just merged #457 which resolves this issue. Thanks for the clean PR, @mclaughlin6464.
