### ISSUE TITLE
Add documentation of how `halo_num_satellites` and `halo_num_centrals` is computed

### ISSUE THREAD

**Issue by aphearin** [astropy/halotools#466]
@yymao says he went looking for this in the `populate_mock` method and hit a dead end.

**Comment by aphearin** [comment]
PR #521 should resolve this issue, @yymao. 

Tagging @nickhand who had also requested that a tutorial on the HOD mock-making algorithm be included in the documentation. 

Feedback on the new sections addressing this documentation would be great, but I understand the two of you may have moved on and that this tutorial is rather involved. If you don't have time to read the tutorial but could comment on its "discoverability", that would also be helpful. Regardless, thanks for pointing out the necessity of this section of the docs.

**Comment by nickhand** [comment]
This tutorial looks great -- it's exactly what I had in mind for this section. Thanks for adding it!

I do have a somewhat related issue that I was wondering about while reading through the tutorial about setting random seeds when populating mocks. I've opened up #551
