### ISSUE TITLE
The mass cut in hod_mock_factory should throw an informative error if all halos are removed. 

### ISSUE THREAD

**Issue by mclaughlin6464** [astropy/halotools#473]
When calling populate_mock on a halocat, some initial operations are run on that halocat as the mock object are created. Among these is a so-called "trivial" mass cut (line 123 of hod_mock_factory). I made a mistake when caching my catalog and my mass column was misdefined, and the cut removed all my halos. However, I didn't realize a mass cut was performed at all, and it took some digging to figure out what happened. In this instance where all or even most halos are removed from a catalog, an error should be thrown, suggesting either the user made a mistake defining their cached catalog or there is a problem with their halocat itself.

**Comment by aphearin** [comment]
Thanks for pointing this out @mclaughlin6464 - I'll address this very soon.

**Comment by aphearin** [comment]
@mclaughlin6464 - let me know whether this commit would have made your life easier, or if you have other suggestions for how this would have been easier to track down:

https://github.com/aphearin/halotools/commit/75f85ad864449dd7ea64b9554d49550714290cd4

Also, can you also clarify a bit more what happened with your "misdefining" the mass column? Depending on exactly what happened, I might like to add additional measures at multiple entry points to protect against what you experienced. For example, if you accidentally cached an empty halo catalog, that should have raised flags as well. 

If other aspects of the catalog processing could have been more transparent, feel free to comment either here or in an independent issue.

**Comment by mclaughlin6464** [comment]
Yes, the above commit would've fixed the issue.

And to clarify, when reading in the catalog I put the wrong column down for mvir and it read in a list of id's or something. So, none of the numbers were > 1e13 or so, so they were all cut.

**Comment by aphearin** [comment]
Right, that's what I suspected happened. Super common, happens to me all the time. I wish there were something I could do about that at the level of the reader, but there are so many different versions of Rockstar floating around and there is nothing approximating a standardized header. 

Thanks again for the feedback.
