### ISSUE TITLE
major bug in pair-counting test suite

### ISSUE THREAD

**Issue by aphearin** [astropy/halotools#49]
@duncandc - I just updated my master branch with your latest changes. Did you run the test suite before submitting your PR? When I run the test suite, not only are new errors produced, but in fact, the entire execution of the test suite just fails and the system exits before the suite is done running. 

@eteq - how can such a thing happen, anyway?

**Comment by aphearin** [comment]
In one week, I'll be leaving town on two trips dedicated to working with collaborators in which I will be heavily using Halotools, so this bug is very poorly timed. I simply deleted the offending test module (test_two_point_functions.py). 

After deleting that, the test suite ran just fine. So then I also went ahead and merged my rough draft of the sim_manager sub-package. As of the time of this writing, the above bug does not occur anymore, and the master branch has had a major update with the sim_manager package. 

Let's come back to this when @duncandc has time to clean up the mock_observables sub-package, including the complete deletion of the pair counters that are now obsolete. We'll deal with this bug if/when it recurs.

**Comment by duncandc** [comment]
This is happening because there is a seg fault in the sinha pair counting because the wrapper can only handle PBCs.  The fix nearly done.  Ill put this up later today, and all modules should compile and pass their tests!

**Comment by aphearin** [comment]
Outstanding.

**Comment by duncandc** [comment]
This should be fixed in latest pull request.
