### ISSUE TITLE
Add regression test for rtd.io

### ISSUE THREAD

**Issue by aphearin** [astropy/halotools#504]
Add test to suite ensuring that the substring "readthedocs.org" never appears in any repo file. There is already a self-reading test module whose pattern can be matched: halotools/tests/test_amurrica.py

CC @bsipocz

**Comment by bsipocz** [comment]
Wow, you take testing very seriously :smile: 

However this is far from being critical, a snipset from the RTD post about the change (io vs org domain), so even if the org is used it should work:
```
Projects will automatically be redirected, and this redirect will remain in place for the foreseeable future. Still, you should plan on updating links to your documentation after the new domain goes live.
```

On the other hand what would be quite useful is to have a script that checks whether all the external links in a repo work. Then optionally this can be build into the ``remote-data`` testing option.

**Comment by aphearin** [comment]
yeah, ok, this is overkill. I guess I've just got testing on the brain lately. 

I started fooling around with the auto-detection feature you described and made some headway. This is sort of fun. I'll tag you if I get anywhere useful/robust with it.
