### ISSUE TITLE
Bug in tpcf_jackknife

### ISSUE THREAD

**Issue by aphearin** [astropy/halotools#513]
Significant bug in `tpcf_jackknife` function due to incorrect implementation of error_estimation_tools.jackknife_covariance_matrix. The jackknife_covariance_matrix has been entirely deleted from the repo as it was entirely redundant with numpy.cov. 

@mclaughlin6464 - my apologies if you have been using this function for science purposes. The jackknife errors you were getting by using `tpcf_jackknife` were surely incorrect. I have a bug-fix PR that I will submit momentarily.

**Comment by mclaughlin6464** [comment]
No worries, I haven't been using it in detail. However I'll make sure to make sure to pull down these new changes for the future. Thanks for for notifying me!
