### ISSUE TITLE
Add unit-testing against external code for `wp`

### ISSUE THREAD

**Issue by aphearin** [astropy/halotools#546]
As suggested in #544 by @surhudm, there should be additional unit-testing of `mock_observables` in which the output of the user-facing functions is compared to external codes operating on the same inputs. 

Currently, the pair-counters and bounds-checking functions are well-tested, but the current test suite in many cases does not verify the correctness of the algebraic manipulations internal to the `wp` function. Evidently, @manodeep has already done such comparisons and can confirm that `halotools` and `corrfunc` agree within floating point precision. It would be good this specific comparison could be incorporated into the test suite itself. @manodeep - would you be willing to provide the `corrfunc` output and the associated commit of the version producing the result if I provided you with the samples, rbins, etc? I think this test would be more compelling if the operation of `corrfunc` were handled entirely by its author.

**Comment by manodeep** [comment]
@aphearin Send me the samples, rbins and I will give you the output wp.

**Comment by aphearin** [comment]
Ok, great, thanks!
