### ISSUE TITLE
Add documentation note for optimization flags

### ISSUE THREAD

**Issue by aphearin** [astropy/halotools#564]
Forcing certain compiler optimization flags can lead to Halotools being less robust to install, especially on older machines, as pointed on #561. In the short term, rather than determining the cython compiler flags in a fancy automated fashion, the simple way forward is just to add a note to installation section of the documentation informing performance-hungry users to build their own version from source, throwing their own flags as necessary. This is probably a pretty small thing to ask of a typical user who is interested enough in optimizing performance a the ~25% level. And anyway, there are at least factors of 2-3x speedups that can be gained simply from grinding down the source code implementation of the pair-counting algorithm, so labor this automation should play second fiddle to those changes. *After* the next iteration on the pair counting engines (which will probably not be utill v0.5), revisit the issue of automated compiler flag optimization.

**Comment by ngoldbaum** [comment]
FWIW, yt tests for openmp support by trying to compile a simple program:

https://bitbucket.org/yt_analysis/yt/src/d48c4a143f6e3c69c9a1016725d8328f8ea3af53/setupext.py?fileviewer=file-view-default#setupext.py-9

(see also setup.py in the same directory)

It's definitely not very foolproof or general, but at least there's a simple way to check for support and then not fail the entire compilation step.

If you're really worried about compilation issues, I'd urge you to think about uploading binary wheels and building conda packages, which sidesteps the compilation issue entirely.
