### ISSUE TITLE
correct BolshoiP particle mass

### ISSUE THREAD

**Issue by aphearin** [astropy/halotools#576]
The particle_mass attribute of the Bolshoi-Planck simulation is incorrect, stemming from an incorrect posted value on the CosmoSim website. The correct value is 1.48e8 Msun/h. Thanks to @surhudm for pointing this out.

**Comment by johannesulf** [comment]
Not sure it's 1.48, either. https://www.cosmosim.org/cms/simulations/bolshoip/ lists 1.55 and all M_vir in the halo catalog are multiples of 1.55e8. So 1.55e8 Msun/h seems to be the correct answer.

**Comment by surhudm** [comment]
Thanks Johannesulf!

Hey Andrew,

>>> import numpy as np
>>> gee = 4.2994e-9
>>> rhocrit = 3.E4/(8.*np.pi*gee)
>>> rhobar = rhocrit*0.30711
>>> print rhobar/(2048.**3)*250.0**3/1.E8
1.55094954611

What gives?

Cheers,
Surhud

**Comment by aphearin** [comment]
@surhudm - I'm not sure how @andrew-zentner arrived at 1.48, but when I created this issue I just basically copied and pasted text from an email chain to remind myself later to calculate it myself and fix it. I agree with you and Johannes though. I'll add the fix when I release `v0.4` next week.

**Comment by aphearin** [comment]
This is resolved in #614.
