### ISSUE TITLE
wp tutorial has wrong equation for wp(rp)

### ISSUE THREAD

**Issue by surhudm** [astropy/halotools#580]
The tutorial for wp(rp) computation has the wrong equation for wp(rp). 

https://github.com/astropy/halotools/blob/master/docs/quickstart_and_tutorials/tutorials/catalog_analysis/galcat_analysis/basic_examples/clustering_examples/galaxy_catalog_analysis_tutorial4.rst

The equation as written gives a dimensionless number and has an erroneous multiplication factor of 2 \pi_{max} compared to the commonly used definition.

It is easily fixable, but it also requires the associated figures to be updated.

**Comment by aphearin** [comment]
Yes, agreed. Such are the consequences of hurrying. I'll fix this soon, thanks again.
