### ISSUE TITLE
pairwise_distance API bug

### ISSUE THREAD

**Issue by duncandc** [astropy/halotools#599]
In pairwise_distance_3d() and pairwise_distance_xy_z() r_max,or rp_max and pi_max, is supposed to accept array arguments.  The purpose of this is to customize the search radius around each point in data1.   

I swear I changed this in the past, but I see no evidence of this being removed in the logs of these files.  @aphearin, was this feature removed and the doc string not changed to represent this?  If so, I really like this feature.  On the other hand, if this is just an oversight, I will put in a pull request to fix it.

@johannesulf, are you using this code?

**Comment by johannesulf** [comment]
@duncandc I'm not using this code.

**Comment by aphearin** [comment]
Not sure what happened to your version, @duncandc. It would be great if you could bring it in though.

**Comment by aphearin** [comment]
This is resolved by #602.
