### ISSUE TITLE
Moster13SmHm little h

### ISSUE THREAD

**Issue by duncandc** [astropy/halotools#605]
It is ambiguous in the paper what the units are.  It appears by trial and error it should be h=1.

**Comment by aphearin** [comment]
@duncandc - I think you mean Moster10SmHm, yes?

**Comment by duncandc** [comment]
http://halotools.readthedocs.io/en/latest/api/halotools.empirical_models.Moster13SmHm.html#halotools.empirical_models.Moster13SmHm

**Comment by aphearin** [comment]
There was no bug in the implementation. But #620 improved the documentation and in-line comments.
