### ISSUE TITLE
Documentation error: DownloadManager()

### ISSUE THREAD

**Issue by johannesulf** [astropy/halotools#628]
The very first example of the DownloadManager() documentation has an error. It now reads `halo_finder = sim_defaults.default_version_name` , but should be `halo_finder = sim_defaults.default_halo_finder`.

(Maybe one could also add `from halotools.sim_manager import sim_defaults` at the beginning of the example.)

**Comment by aphearin** [comment]
Thanks for #654, @johannesulf!
