### ISSUE TITLE
Should HodModelFactory and HodMockFactory have a different API for populating?

### ISSUE THREAD

**Issue by mclaughlin6464** [astropy/halotools#631]
Very minor gripe. I noticed that HodModelFactory has a function populate_mock, but HodMockFactory's companion function with similar use and arguments is called populate. Is there a reason they are different?

**Comment by aphearin** [comment]
`populate_mock` requires a positional argument of a halocat and automatically triggers the whole pre-processing phase from scratch. The `populate` method only works after the whole pre-processing phase is done, so it is typically an order of magnitude faster. I gave them different names to stress that these functions are called in different contexts.

**Comment by mclaughlin6464** [comment]
I see. That is a fair design decision, I was at first confused because they seem similar in their use.

**Comment by aphearin** [comment]
Roger. Will address this in #632.
