### ISSUE TITLE
Zheng07 composite model: modulate_with_cenocc not passed to Zheng07Sats?

### ISSUE THREAD

**Issue by johannesulf** [astropy/halotools#646]
It seems that the keyword argument modulate_with_cenocc for the Zheng07 composite model is not passed to the Zheng07Sats occupation component. The Zheng07Sats occupation component always uses modulate_with_cenocc=False.

https://github.com/astropy/halotools/blob/master/halotools/empirical_models/composite_models/hod_models/zheng07.py#L17

The simple code `model = PrebuiltHodModelFactory('zheng07', modulate_with_cenocc=True)` results in the warning message `UserWarning: You chose to input a ``cenocc_model``, but you set the 
``modulate_with_cenocc`` keyword to False, so your ``cenocc_model`` will have no impact on the model's behavior.
Be sure this is what you intend before proceeding.
Refer to the Zheng et al. (2007) composite model tutorial for details.`

**Comment by aphearin** [comment]
Good catch, Johannes. At least that explicit warning was in there. I think this must be related to #577, and some changes suggested by @mclaughlin6464 that I must not have finished porting through to the rest of the package. Should be an easy fix.

**Comment by aphearin** [comment]
This is resolved by #647.
