### ISSUE TITLE
RTD documentation build failure

### ISSUE THREAD

**Issue by aphearin** [astropy/halotools#658]
RTD now fails to build - must have been triggered either by #655 or #657, probably the former since that PR actually changed a documentation module.

**Comment by bsipocz** [comment]
What do you mean by rtd failure? Could you link a log here? It seems to me that all the recent builds are passed, based on this: http://readthedocs.org/projects/halotools/builds/

**Comment by aphearin** [comment]
Yes, you seem to be correct. This must have been a temporary issue that was resolved after wiping.
