### ISSUE TITLE
Travis & AppVeyor build failures 

### ISSUE THREAD

**Issue by aphearin** [astropy/halotools#710]
Currently, the master branch of the code fails many tests on Travis, and does not pass on AppVeyor either. The failures are somewhat mysterious as well - on Travis, the tests simply stop running; on AppVeyor there is a `MemoryError` that occurs during different tests, depending on the build. Moreover, these failures first occurred during #703, a simple docstring edit which could not possibly be the source of the failure. Additionally, the code passes all tests locally on `APH_MACHINE`. This makes me think that the code had just been operating near the maximum memory capacity of the virtual machines used by these CI services, and that there was possibly some server-side config change that triggered the failures. This hypothesis can be tested by re-building a previously accepted PR.

Several of the current PRs definitely improve the memory load during testing (e.g., #709 and #705), and others surely have zero impact (e.g., #703 and #704), so I'm going to merge these even though they cause CI build failures. 

Note: the `v0.5` release is now in a feature-freeze. Basically the only thing that remains is to resolve this issue and then the code will be ready for release. 

@bsipocz and @eteq - I had tagged you in #704 to discuss this, but I'm going to go ahead and merge that, so in case you have further input on how to resolve this, let's migrate discussion to this channel. @eteq said he might try and find time to just replicate the Travis VM and dial down the memory to try to reproduce the error, which would be super helpful.

**Comment by bsipocz** [comment]
@aphearin - Sadly travis swallows many of the errors which leads to misleading or mysterious situations (we saw this halting of logs with e.g. numpy prerelease testing where the solution was to install ``nomkl`` with the prerelease). So while @eteq's idea about running our of memory is probably the culprit I would also check with the version numbers of all the packages installed.

E.g Comparing job2 in the last [successful build](https://travis-ci.org/astropy/halotools/jobs/209570649) before the [failing one](https://travis-ci.org/astropy/halotools/jobs/211335154) shows a difference in scipy version. Which one of those do you have locally with the passing tests?

```
============================= test session starts ==============================

platform linux -- Python 3.5.3, pytest-2.8.3, py-1.4.30, pluggy-0.3.1

Running tests with halotools version 0.5.dev262.

Running tests in lib.linux-x86_64-3.5/halotools docs.

Date: 2017-03-10T01:45:23

Platform: Linux-4.8.12-040812-generic-x86_64-with-debian-wheezy-sid

Executable: /home/travis/miniconda/envs/test/bin/python

Full Python Version: 

3.5.3 |Continuum Analytics, Inc.| (default, Mar  6 2017, 11:58:13) 

[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8

byteorder: little

float info: dig: 15, mant_dig: 15

Numpy: 1.12.0

Scipy: 0.18.1

Matplotlib: 2.0.0

h5py: 2.6.0

Astropy: 1.3

Using Astropy options: remote_data.
```

Vs

```
platform linux -- Python 3.5.3, pytest-2.8.3, py-1.4.30, pluggy-0.3.1

Running tests with halotools version 0.5.dev254.

Running tests in lib.linux-x86_64-3.5/halotools docs.

Date: 2017-03-18T20:14:14

Platform: Linux-4.8.12-040812-generic-x86_64-with-debian-wheezy-sid

Executable: /home/travis/miniconda/envs/test/bin/python

Full Python Version: 

3.5.3 |Continuum Analytics, Inc.| (default, Mar  6 2017, 11:58:13) 

[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8

byteorder: little

float info: dig: 15, mant_dig: 15

Numpy: 1.12.0

Scipy: 0.19.0

Matplotlib: 2.0.0

h5py: 2.6.0

Astropy: 1.3

Using Astropy options: remote_data.
```

**Comment by bsipocz** [comment]
also in cases like this, you can add ``DEBUG=True`` to the global variable in travis. That will go very verbose for the installs which may be valuable when you try to install the same conda environment somewhere else.

**Comment by aphearin** [comment]
Re: scipy - good catch on the version change. However, on my local machine, I have 0.19 installed. 

Re: `DEBUG=True`. Haven't used that before, but that sounds very helpful since the tests just poop out without explanation.

**Comment by aphearin** [comment]
In #713, there are several minor changes throughout the test suite in an attempt to resolve this. In many cases, all I did was inspect the build log to see where the tests stop running, identify the specific test, confirm that it is indeed a very memory-intensive one, and then add a simple decorator on it: `@pytest.mark.skipif('not APH_MACHINE')`. Similarly, there were a few docstring tests to which I added `# doctest: +SKIP`. I'm not all that happy with this resolution, because in several cases such as `leauthaud11_composite_model.rst` and `tinker13_composite_model.rst`, I really do want the mock-population to proceed as part of the doctests.

The other kind of "failure" I noticed was for tests of functions using several cores, such as the `mock_observables` functions that use the `multiprocessing` module to divvy up pair-counting. In some cases, the multi-threading was only being used to speed up the test execution, so I just changed those tests to run in serial. In other cases, it was actually very important to run the test in parallel because the specific purpose of the test was to explicitly verify that the function returns the same result whether it is run in parallel vs. serial. For those tests, I just again used the `@pytest.mark.skipif('not APH_MACHINE')` decorator.

**Comment by bsipocz** [comment]
@aphearin - Unfortunately I don't know about a way to have a similar decorator for the doctests. What about factoring out that code into a script, and wrap it in both a test file, and include also in the docs? It's not ideal, but that case it still get tested, and you don't need to maintain the examples in two places.
