### ISSUE TITLE
Inconsistent notation between OccupationComponent and Kravtsov04Cens

### ISSUE THREAD

**Issue by aphearin** [astropy/halotools#72]
This was pointed out by @andrew-zentner . ARZ: would you mind describing the source of confusion here in this GitHub issue?

**Comment by andrew-zentner** [comment]
Slightly different keywords associated with the __init__ method of OccupationComponent and Kravtsov04Cens. For example, I noticed that in the former, you assume keyword 'param_dict' while in the latter, you assume keyword 'input_param_dict'. It would be more readable, in my opinion, for these to be identical.

**Comment by aphearin** [comment]
Roger. Will fix this and close this Issue when it is fixed.
