### ISSUE TITLE
HeavisideAssembias not picklable

### ISSUE THREAD

**Issue by mclaughlin6464** [astropy/halotools#741]
I'm having difficulty pickling an instance of the HeavisideAssembias object while using emcee multiprocessing. Specifically, it's balking at trying to pickle the new_haloprop_func_dict, as it contains references to functions which are not picklable. I tried the solution laid out [here](http://stackoverflow.com/questions/11726809/python-efficient-workaround-for-multiprocessing-a-function-that-is-a-data-membe) (pasted that code into my instance) to no avail. I'm trying to find a solution that does not entail rewriting the full functionality of the new_haloprop_func_dict, but I'm having difficultly finding such a solution.

**Comment by aphearin** [comment]
As a hacky workaround, can you just manually add a new column to the halo catalog you will be populating? Or does your use-case make this too awkward?

**Comment by mclaughlin6464** [comment]
Looking more closely at my use case, I do not need to populate a catalog, so I don't load a specific table. I'm just accessing the mean functions. So I was able to just delete that element of the new_haloprop_func_dict. However, emcee then balked at pickling "wrapper." I found a workaround to this [here](http://gael-varoquaux.info/programming/decoration-in-python-done-right-decorating-and-pickling.html).  However, now emcee is mad that it can't pickle an instance of "mean_occupation", the decorated function. This I can't quite figure out.

**Comment by mclaughlin6464** [comment]
I've currently using a workaround that has the models in the global scope, so they don't have to be pickled. However, in general, this would be a good feature to have, especially for using the models in a parallel MCMC scenario.

**Comment by aphearin** [comment]
I seem to remember this coming up at some point during the likelihood analyses run by the NYU group, so asking @mjvakili @changhoonhahn @kilianbreathnach if they have encountered this before and solved it in some other way. 

I know @andrew-zentner specifically has run MCMCs with emcee using decorated HODs, so maybe he also has experience addressing this.

**Comment by kilianbreathnach** [comment]
What I've used to get around pickling issues with emcee when using halotools sounds like it is probably the same workaround that @mclaughlin6464 has arrived at. If your use case isn't too complicated and you need an instance of a certain class to be accessible within each process, you can declare a global variable and pass it to the `Pool` instance of `multiprocessing` that your sampler uses. To do this you need to define an initialising function which declares the global variable and pass it as a parameter to an emcee `InterruptiblePool` instance which you then pass to your sampler. Here is an example of how I've done this:

```
import emcee
from emcee.interruptible_pool import InterruptiblePool

def initfunc():
    global inst
    inst = MyClass()

pool = InterruptiblePool(nthreads, initializer=initfunc)
sampler = emcee.EnsembleSampler(nwalkers, ndim, lnprob, pool=pool,
                                args=(arg1, arg2, arg3),
                                threads=nthreads)
```

I'm not sure if it would come up for me in sampling to do something more demanding than this but I'd be interested to know a proper solution to this problem too.

**Comment by aphearin** [comment]
@kilianbreathnach and @mclaughlin6464 - do either of you know whether this is a problem with *all* halotools models, or just assembly biased ones?

**Comment by mclaughlin6464** [comment]
@aphearin The problem is that you can't pickle references to functions. So, most objects seem to tacitly support a new_haloprop_func_dict, but the only case I know its explicitly used is HeavisideAssemblyBias. Since new_haloprop_func_dict carries function references it can't be pickled. Additionally, the way HeavisideAssemblyBias decorates the baseline function also seems to create issues. I tried to wrap the `wrapper` function but it didn't completely solve the issue.

**Comment by aphearin** [comment]
I see. That is pretty good news, I think. The `new_haloprop_func_dict` is a largely unnecessary piece of machinery. And the function decoration is also easily replaced with a simple override. Good to know.

**Comment by mclaughlin6464** [comment]
Those are the issues that I'm aware of, but I think they're the only major features of an Assembias object.
