### ISSUE TITLE
Add external verification for Cacciato09 CLF models

### ISSUE THREAD

**Issue by johannesulf** [astropy/halotools#758]
So far, Cacciato09Cens and Cacciato09Sats are missing external verification. Some data from @surhudm's paper (arxiv:1207.5508) on magnitude gap statistics would be ideal. Specifically, matching the analytic prediction in Fig. 1 of that paper for log M = 14.5 would be a strong test as the magnitude gap of the brightest and 2nd brightest galaxy depends on the entire CLF for centrals and satellites.

@surhudm Could you send me a text file with the cumulative distribution function of magnitude gaps sampled with 1000 points from 0 to 3 mag? As discussed, there's no rush.

**Comment by surhudm** [comment]
Sent a file to @johannesulf with the green solid line from Figure 1 of arxiv:1207.5508, P(Delta m_12|M,N) where M=10^14.5 Msun/h and N=21 (Nsat=20). The cumulative distribution function should be reasonably easy to compute based on that.

**Comment by johannesulf** [comment]
Using a KS-test, the Monte-Carlo results for the gap using halotools are consistent with the analytic prediction. I tested this for up to 1000000 magnitude gaps produced in the Monte-Carlo simulation.

**Comment by johannesulf** [comment]
Yes, I changed the CLF parameters to the ones from Cacciato et al. 2012. I don't think the agreement would be that good otherwise.
