### ISSUE TITLE
npairs_s_mu performance

### ISSUE THREAD

**Issue by aphearin** [astropy/halotools#763]
As pointed out by @manodeep - the `npairs_s_mu` has needless usage of square roots inside tight cython loops. In exactly the same fashion as with pair counting in Cartesian bins, the engine can be passed `mu_squared_bins` and `s_squared_bins` to avoid this. No changes to the python API are required, this can be handled entirely with a small change to internal variables. 

CC @duncandc @johannesulf @sssaito - I don't know whether performance has been a major problem for y'all, but this will likely speed up `npairs_s_mu` quite substantially.

**Comment by duncandc** [comment]
I haven't noticed s_mu_tpcf being slow, but we should definitely fix this no-brainer issue.

**Comment by manodeep** [comment]
I only took a closer look at the source because `npairs_s_mu` took ~100 seconds on my laptop for the `Mr19` galaxy catalog in `Corrfunc`. For comparison, the equivalent `Corrfunc/theory/DDrppi` takes about 8 seconds on my laptop.

**Comment by aphearin** [comment]
@duncandc - I can handle modifying the internals since it'll just take a second to get a major speedup - but it's uncomfortable to modify these kernels without a reliable brute-force unit-test to calibrate against. Having the `npairs_s_mu` comparison that Shun gave you would be helpful while grinding down the performance.

**Comment by aphearin** [comment]
Actually, @manodeep - since you have recently worked with both codes for the same calculation, would it be easy for you to provide a set of point data, bins, and `npairs_s_mu` counts?

**Comment by duncandc** [comment]
I'll work on the test.  Let me know if someone else is taking over.

**Comment by manodeep** [comment]
@aphearin - that's funny. I was using `halotools` for the test case of known *correct* output :). 

Once I have finished my xi_s_mu (~ month), I will have at least one set of brute-force counts. Happy to send that upstream. I thought @sssaito did have a version of xi(s, mu) derived from the initial (Aspen) version of Corrfunc.

**Comment by manodeep** [comment]
Just created a pull request with the patch. 

On a related note, the inline docs for keep saying `sine` function in the `NOTES` for `mu` in [npairs_s_mu.py](https://github.com/astropy/halotools/blob/master/halotools/mock_observables/pair_counters/npairs_s_mu.py#L63) but the first line of doc says [`cos`](https://github.com/astropy/halotools/blob/master/halotools/mock_observables/pair_counters/npairs_s_mu.py#L60) Why the mis-match?

**Comment by duncandc** [comment]
The description of mu_bins in the doc string is wrong.  It should be sin(theta).

**Comment by duncandc** [comment]
O, and I see. yes, the first line should also be cos(theta).

**Comment by manodeep** [comment]
I saw the note, but shouldn't the expectation be that the user passes in `cos(theta)` bins, halotools then internally converts those to `sin(theta)` bins and then does the calculations. I assume there is some increasing order required for the bins, so the bin counts would have to be reversed at the end along the `mu` axis but that seems fairly easy to do.

**Comment by manodeep** [comment]
Same for [s_mu_tpcf](https://github.com/astropy/halotools/blob/master/halotools/mock_observables/two_point_clustering/s_mu_tpcf.py#L61)

**Comment by duncandc** [comment]
It would be okay with me if the s_mu_npairs engine did the conversion from cos to sin.  But if we change that, we need to change how the mu_bins are processed in the s_mu_tpcf() function.

I have a slight preference for the engines to do almost no processing of the arguments.  So, as long as the doc string makes clear mu_bins are sin(theta_LOS), i don't see a problem.

**Comment by duncandc** [comment]
s_mu_tpcf() expects mu=cos(theta_LOS) bins.

**Comment by manodeep** [comment]
I agree with minimal processing of arguments in the Cython engines. However, the `npairs_s_mu.py` engine could certainly handle the transformations from `cos->sin` **and** from `sin->cos`. Any change in `s_mu_tpcf` would be internal only and not exposed to the user.

**Comment by duncandc** [comment]
That's right.

**Comment by aphearin** [comment]
@duncandc - I think the original motivation for sin(theta) instead of the standard cos(theta) was something to do with having monotonically increasing separation bins, no? I could be wrong though.

**Comment by duncandc** [comment]
That was it.  Although, I do not remember why that was necessary.  However, I think npairs_s_mu() could convert from cos to sin.  Then that is almost entirely hidden from most users.  After cleaning up the doc strings, it shouldn't be confusing anymore.

**Comment by duncandc** [comment]
I am happy to take care of this this afternoon if we all agree.

**Comment by manodeep** [comment]
I am happy with that. This way the user expectation of `cos(theta)` as `mu` is fine, and the internal cython enginess get the nice and monotonically increasing `sin(theta)` as the `new mu` bins.

**Comment by aphearin** [comment]
Yes @manodeep - exactly right. It's unfortunate that the user-facing API will change, but I think in this case that is really for the better.
