### ISSUE TITLE
Subsampling marks when `max_sample_size` is reached

### ISSUE THREAD

**Issue by manodeep** [astropy/halotools#797]
While computing a [marked correlation function](http://halotools.readthedocs.io/en/latest/api/halotools.mock_observables.marked_tpcf.html), I get the following error from `halotools`:

    HalotoolsError:
    You passed in a 2-D array for `weights2` that
    does not have a consistent shape with `sample2`.
    `sample2` has length 1000000. The input value of `weight_func_id` = 1
    For this value of `weight_func_id`, there should be 1 weights
    per point. The shape of your input `weights2` is (2097152, 1)

I can fix this by simply setting `max_sample_size=bazillion`. 

However, if random down-sampling is applied to the sample, then that **exact** same (random) subsampling should also be applied to the `marks`/`weights`. Good news is that since `halotools` throws the error I got, it will never return any incorrect results.

**Comment by aphearin** [comment]
@manodeep - yeah, I've been using the same workaround myself. I can't really remember why this feature is even in there - maybe a relic of when the code was really slow? Maybe @duncandc remembers. In any case, I use the code with 10^7 points all the time to compute cluster lensing signals for very large mocks, so I also find this annoying. The code runs perfectly fine in this regime, even if not at MCMC speeds. 

Proposed solution: eliminate this feature entirely. Any objections from either @manodeep or @duncandc?
