### ISSUE TITLE
model.mock.estimate_ngals() doesn't work for composite HOD model

### ISSUE THREAD

**Issue by KuanWang-Astro** [astropy/halotools#801]
![image](https://user-images.githubusercontent.com/16751577/29795221-4b215d02-8c19-11e7-94db-95fc2b0961ef.png)
When I populate the halo catalog with this model, the estimate_ngals() method gives back an error:
![image](https://user-images.githubusercontent.com/16751577/29795268-83b0561e-8c19-11e7-90de-55793f991e08.png)
while the following works.
![image](https://user-images.githubusercontent.com/16751577/29795294-9dc3b44c-8c19-11e7-832a-2758feed40c6.png)
The only difference should be the HOD model.

**Comment by aphearin** [comment]
Thanks for pointing this out @KuanWang-Astro - should be an easy fix.
