### ISSUE TITLE
simple installation testing

### ISSUE THREAD

**Issue by aphearin** [astropy/halotools#803]
There should be a *much* shorter, but still reliable and robust, way for users to run a test suite to verify that they have a successful installation. And the documentation for this should be immediately discoverable for people who want to quickly pip install and get going. 

@eteq -if you have a suggestion right away, feel free to post here. Otherwise, let's discuss on Slack sometime soon. This has come up repeatedly, since the full test suite can take tens of minutes, which is sure to only become worse over time.

**Comment by eteq** [comment]
@aphearin - I think this is the way to go:  first choose some name for the subset of tests that are "installation tests".  Then mark them with the `@pytest.mark` decorator as, say "installation_test".  Then in the halotools __init__.py, add something like following:
```
def test_installation(*args, **kwargs):
    kwargs['kwargs].set_default('-k installation_test')
    test(*args, **kwargs)
```
