### ISSUE TITLE
Add weighted version of `(s, mu)` pair-counting

### ISSUE THREAD

**Issue by aphearin** [astropy/halotools#809]
Feature requested by @sssaito, who should comment here on the specific input/output that is needed. I *think* what is requested is a variation of the existing `halotools.mock_observables.pair_counters.npairs_s_mu` function, but rather than updating the returned counts histogram with an integer for every pair, instead the histogram is updated with `w_1*w_2`, where `w_1` and `w_2` are weights associated with point 1 and point 2. But I am not sure, so @sssaito should confirm or correct.

**Comment by sssaito** [comment]
Yes, I confirm it is correct. Also, I would like to have a feature like `rbins_normalized` in `halotools.mock_observables.radial_profiles.radial_profile_3d` but I guess this can be realized as a separate function once `npairs_s_mu` is realized.

**Comment by aphearin** [comment]
Ok, thanks for clarifying. 

Let's start with a new function `weighted_npairs_s_mu`, and then after that in a separate issue we can move on to either:

1. another new function `profile_s_mu`, or 
2. an additional `normalize_by` keyword argument for the `weighted_npairs_s_mu`
