### ISSUE TITLE
tpcf jackknife covariance matrix normalization error

### ISSUE THREAD

**Issue by duncandc** [astropy/halotools#815]
The covariance matrices in the tpcf_jackknife() mock_observables function aren't correctly normalized. 

The tpcf_jackknife() function uses the numpy.cov() function to calculate the covariance matrix which normalizes by default using 1/(N-1) where N is the number of samples.  For jackknife samples, it should instead be normalized by (N-1)/N.    

Thanks to @yymao for the consultation on this matter.

**Comment by aphearin** [comment]
CC @tmcclintock - you should be aware of this bug. We are fixing asap. I will re-release `v0.6` of the code very soon, possibly even this week, next week for sure. Until then, after the bugfix PR, you can use the bleeding edge version by cloning `master` and building from source. Apologies if this bug caused you problems in your work.

**Comment by tmcclintock** [comment]
I'm pretty sure [this is the line](https://github.com/astropy/halotools/blob/93b665f1430d65cb196517dce90c6dee7d8797ea/halotools/mock_observables/two_point_clustering/tpcf_jackknife.py#L292), as well as the following two, that need fixing.

According to the [numpy docs](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.cov.html) you need to use either the ```bias``` argument or the ```ddof``` argument. If you use ```bias``` then (without having checked this myself...) you will reproduce what you have now if you use ```bias = Nsub**3 - 1```, and the correct behavior is obtained if you use ```bias = (Nsub**3 - 1.)/Nsub**3```.

Apologies for being too lazy to PR.

**Comment by aphearin** [comment]
No apologies necessary, Tom, this is super helpful. Many thanks!

**Comment by tmcclintock** [comment]
Oops it isn't ```Nsub**3```, it is the product of all the the elements of ```Nsub```.

**Comment by duncandc** [comment]
Right, I believe bias must be a boolean. Take a look at the current fix.  I believe we are in agreement.

**Comment by tmcclintock** [comment]
Ah true. I misread the numpy docs.

**Comment by aphearin** [comment]
Resolved by PR #818
