### ISSUE TITLE
Possible Python 3.6 compatibility issue

### ISSUE THREAD

**Issue by johannesulf** [astropy/halotools#826]
I just switched to python 3.6 and now encounter a problem with reading any halo catalog. The following code snippet gives an error under python 3.6 but runs fine under python 2.7 on the same machine. I use halotools 0.5 install from pip.

```
from halotools.sim_manager import CachedHaloCatalog

halocat = CachedHaloCatalog(simname='bolplanck', redshift=0)
print(halocat.fname)
print(halocat.halo_table)
```

The important error message is probably the following.

> b'/home/johannes/.astropy/cache/halotools/halo_catalogs/bolplanck/rockstar/hlist_1.00231.list.halotools_v0p4.hdf5'
> ....
> astropy.io.registry.IORegistryError: Format could not be identified.
> ...

Inserting the following line before halocat.halo_table resolves the issue.

`halocat.fname = halocat.fname.decode("utf-8")`

This looks like an issue with halocat.fname being a byte literal. As far as I understand, python 2.7 would just ignore a byte literal and use it as if it was a string. But python 3.6 doesn't do that. This then leads to an issue with the astropy.Table.read function. Has somebody else tried halotools with python 3.6 and can reproduce the problem? I tried it with 3.5 on another machine and did not encounter the above problem. So I don't know for sure whether this is a universal problem.

**Comment by aphearin** [comment]
Thanks for pointing this out. I think this is probably the same problem as reported in #821. 
Seems like you found an easy fix - I'd like to get to this before releasing v0.6 in December, so hopefully soon.
