### ISSUE TITLE
propagation of keywords when configuring pre-built zheng07

### ISSUE THREAD

**Issue by nickhand** [astropy/halotools#827]
I am trying to configure the pre-built zheng model to use a custom mass column. It's very possible I might be not using this as intended, but I am doing the following:

```python
>>> from halotools.empirical_models import PrebuiltHodModelFactory
>>> model = PrebuiltHodModelFactory('zheng07', prim_haloprop_key='halo_custom_mass', mdef='200c')

>>> for d in model.model_dictionary:
>>>       x = model.model_dictionary[d]
>>>       print(d, getattr(x, 'prim_haloprop_key', None))
centrals_occupation halo_mvir
satellites_occupation halo_custom_mass
centrals_profile None
satellites_profile halo_m200c
```

I think the answer could be that only the "mdef" formatted halo mass columns are supported?
Although it seems to me that ``prim_haloprop_key`` should be getting passed to ``Zheng07Cens`` (the class accepts it as a keyword).

**Comment by aphearin** [comment]
Hmm, it could be that halotools makes a hard requirement for a self-consistent choice of halo boundary and halo mass (halo boundary comes in since satellite positions are generated in `x=r/Rvir`). Marking this as a potential bug to address soon.

**Comment by nickhand** [comment]
I think there are two separate concerns here. Let me explain a little more what we are doing. 

The basic workflow is that the user has a catalog of object positions, velocity, etc, which can be converted into "halos" by specifying a cosmo, redshift, and mass definition. This will add some analytic columns to the catalog based on those parameters, i.e., radius, concentration. Then, the user can specify a halotools model, which will be constructed self-consistently using those parameters, and the halos can be populated with the model. We'd like to be able to pass in those 3 parameters to `PrebuilitHodModelFactory` and have them propagated to the components properly. You can see what we are doing here:

https://github.com/bccp/nbodykit/blob/master/nbodykit/hod.py


Then the problems we ran into:
- `prim_haloprop_key` is not passed to the `Zheng07Cens` class if it is passed as a keyword to  `PrebuiltHodModelFactory` (so it always uses the default mass definition to make `prim_haloprop_key`).
- I don't think there's a good way to support both `mdef` and `prim_haloprop_key`, other than adding explicit checks to see if they disagree (although an exception will be rightly raised eventually). Right now we have the user specify `mdef` and simply assign `prim_haloprop_key` to be the `"halo_m" + mdef` (the default behavior).

**Comment by nickhand** [comment]
This fixes our issue with the Zheng07 model, thanks!
