### ISSUE TITLE
Two failures with Test

### ISSUE THREAD

**Issue by vdbosch69** [astropy/halotools#84]
=================================== FAILURES ===================================
 [doctest] halotools.empirical_models.sfr_components.BinaryGalpropInterpolModel.__init__ 
192         and 90% for massive cluster centrals (:math:`M_{\\mathrm{vir}}=10^{15}M_{\odot}`). 
193         We can use the `BinaryGalpropInterpolModel` to implement this as follows:
194 
195         >>> abcissa, ordinates = [12, 15], [1/3., 0.9]
196         >>> cen_quiescent_model = BinaryGalpropInterpolModel(galprop_key='quiescent', abcissa=abcissa, ordinates=ordinates, prim_haloprop_key='mvir', gal_type='cens')
197 
198         The ``cen_quiescent_model`` has a built-in method that computes the quiescent fraction 
199         as a function of mass:
200 
201         >>> quiescent_frac = cen_quiescent_model.mean_quiescent_fraction(prim_haloprop=1e12)
UNEXPECTED EXCEPTION: IndexError("0-d arrays can't be indexed.",)
Traceback (most recent call last):

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/doctest.py", line 1289, in __run
    compileflags, 1) in test.globs

  File "<doctest halotools.empirical_models.sfr_components.BinaryGalpropInterpolModel.__init__[2]>", line 1, in <module>

  File "halotools/empirical_models/sfr_components.py", line 326, in _mean_galprop_fraction
    mean_galprop_fraction[mean_galprop_fraction<0]=0

IndexError: 0-d arrays can't be indexed.

halotools/empirical_models/sfr_components.py:201: UnexpectedException
______________________________ test_unbiased_nfw _______________________________

    def test_unbiased_nfw():
    	nfw_prof = hpc.NFWProfile()
    	gal_type = 'satellites'
    
    	sat_prof = gpf.GalProfFactory(gal_type, nfw_prof)
    
    	snapshot = FakeSim()
    	composite_model = Kravtsov04()
    	mock = HodMockFactory(snapshot=snapshot, model=composite_model)
    
    	# Check that mc_radii gives reasonable results for FakeSim
    	satellite_boolean = mock.galaxy_table['gal_type'] == gal_type
    	conc_key = mock.model.gal_prof_param_list[0]
    	satellite_conc = mock.galaxy_table[conc_key][satellite_boolean]
    	satellite_radii = sat_prof.mc_radii(satellite_conc)
    	assert np.all(satellite_radii < 1)
    	assert np.all(satellite_radii > 0)
    	# Check that mc_radii scales properly for high- and low-concentrations
    	conc_array_ones = np.ones_like(satellite_conc)
    	conc_array_tens = np.ones_like(satellite_conc)*10
    	high_conc_radii = sat_prof.mc_radii(conc_array_tens)
    	low_conc_radii = sat_prof.mc_radii(conc_array_ones)
    	assert high_conc_radii.mean() < satellite_radii.mean() < low_conc_radii.mean()
    
    	# verify that all mc_angles points are on the unit sphere
    	x, y, z = sat_prof.mc_angles(1000)
    	unit_sphere_pts = np.array([x, y, z]).T
>   	norms = np.linalg.norm(unit_sphere_pts, axis=1)
E    TypeError: norm() got an unexpected keyword argument 'axis'

halotools/empirical_models/test_empirical_models/test_gal_prof_factory.py:74: TypeError
===================== 2 failed, 71 passed in 12.64 seconds =====================

**Comment by aphearin** [comment]
@vdbosch69 - looks like this was solved by updating numpy on your machine, so I'm closing this issue.
