### ISSUE TITLE
hod_modeling_tutorial2.ipynb fails on cell 2

### ISSUE THREAD

**Issue by AstroMike** [astropy/halotools#896]
Not sure if there is a perhaps a version mismatch between the notebooks from github and the astropy version, but I get the following error in hod_modeling_tutorial2.ipynb

AttributeError: 'HaloMassInterpolQuenching' object has no attribute 'populate_mock'

<img width="834" alt="screenshot 2018-03-23 15 14 14" src="https://user-images.githubusercontent.com/5515374/37812916-c30d685c-2eb6-11e8-9d82-c9632c9e434e.png">

**Comment by aphearin** [comment]
That's a bug in the docs, @AstroMike - sorry about that. Only composite HOD models have the `populate_mock` method. The `HaloMassInterpolQuenching` class is just a component model. I will fix the docs before the next release, but in the interim: did you figure out how to use this component and populate mocks? Or are you still stuck?

**Comment by AstroMike** [comment]
I had to put this aside for a bit, but I'll let you know when I have a chance to get back to it. Cheers.

**Comment by aphearin** [comment]
Hey @AstroMike - I started to fix this but realized that this error is actually intentional. Notice that there is a sentence prior to the failing cell pointing out that _component_ models cannot be used to populate mocks - only _composite_ models can do that.
