### ISSUE TITLE
Simple getting started as a contributor docs

### ISSUE THREAD

**Issue by Christopher-Bradshaw** [astropy/halotools#932]
Having not looked at halotools for a year or so, it took a bit of work to remember the code/test workflow that worked with .pyx files. The first time around, this also took me a while. In both cases I worked out that this did what I wanted:
```
python3 setup.py build_ext --inplace # if I changed a .pyx file
cd halotools
pytest [-s -k my_test_seach_string]
```
I'm sure this is very standard and people who work on large, compiled, python projects are probably very used to it. But having this (or a simpler workflow that you use) in a findable place might help new contributors.

**Comment by aphearin** [comment]
The developer docs are definitely lacking! I will be happy to add a new page of the docs dedicated to this. Will get to this before releasing v0.7.

**Comment by aphearin** [comment]
New page added to the docs in #962.
