### ISSUE TITLE
wp example missing a minus sign when defining bin centers

### ISSUE THREAD

**Issue by f-ardila** [astropy/halotools#947]
In `Galaxy Catalog Analysis Example: Projected galaxy clustering`
(https://halotools.readthedocs.io/en/latest/quickstart_and_tutorials/tutorials/catalog_analysis/galcat_analysis/basic_examples/clustering_examples/galaxy_catalog_analysis_tutorial4.html#galaxy-catalog-analysis-tutorial4)

the bin centers are defined `rp_bin_centers = (rp_bins[:1] + rp_bins[1:])/2.` but it should be `rp_bin_centers = (rp_bins[:-1] + rp_bins[1:])/2.` (with a minus sign)

It's minor but lead to some confusion.

**Comment by aphearin** [comment]
Thanks for catching this! I'll be sure to fix before the v0.7 release.
