### ISSUE TITLE
Problem with halo concentration and radius

### ISSUE THREAD

**Issue by WeakDog** [astropy/halotools#948]
I'm now trying to generate mock galaxies using my own halo sample. But I can not continue the working since the halotools requires the information of 'halo_nfw_conc' and 'halo_rvir', which I don't have in my halo catalogue. My question is: Can I still use the halotools to generate the mocks if there is no information of halo's concentration and radius in the halo calalogue?

**Comment by aphearin** [comment]
For the halo radius, you will need to add this column yourself to your halo catalog before trying to populate the mock. You can do this with the `halo_mass_to_halo_radius` function:

`from halotools.empirical_models import halo_mass_to_halo_radius
`

You can do the same thing for the concentration, using whatever c-M relation you prefer, or you can use the one calibrated in [Dutton & Maccio 2014](https://ui.adsabs.harvard.edu/abs/2014MNRAS.441.3359D/abstract) by using the `conc_mass_model` keyword argument:

```
from halotools.empirical_models import PrebuiltHodModelFactory
model = PrebuiltHodModelFactory('zheng07', conc_mass_model='dutton_maccio14')

```

**Comment by WeakDog** [comment]
Thanks, it works
