### ISSUE TITLE
igraph dependency bug

### ISSUE THREAD

**Issue by aphearin** [astropy/halotools#96]
@duncandc - not sure what the problem is yet, but I'm looking into it. Here's the summary:

test_igraph_functionality fails in my virtualenv. The traceback leads to the following:

>           g = igraph.Graph(zip(sources, targets), n=matrix.shape[0], directed=directed,\
                                edge_attrs={'weight': weights},\
                                vertex_attrs={'x':x, 'y':y, 'z':z })
E           AttributeError: 'module' object has no attribute 'Graph'

**Comment by duncandc** [comment]
That is the very last function in groups.py  I am not sure why that is causing an error.  There are if statements that check to see if igraph is installed.

**Comment by aphearin** [comment]
Yup, I see that. Looks like it should work as-written. I'm guessing this does not happen on your machine?

**Comment by duncandc** [comment]
correct.

**Comment by aphearin** [comment]
When I open up a python session, the version of igraph I have installed does not have a module named "Graph". Where did you get your version of igraph?

**Comment by duncandc** [comment]
Well shit.  This is annoying... there are two packages called igraph.  https://pypi.python.org/pypi/igraph/0.1.8 and https://pypi.python.org/pypi/python-igraph/0.7.1.post6

The later is the appropriate one.  I am not exactly sure what the former is...

**Comment by duncandc** [comment]
maybe we should remove this module until we can clean it up?

**Comment by aphearin** [comment]
What would need to be cleaned up besides this one issue?

**Comment by duncandc** [comment]
Nothing.  Either fix the check for igraph, or remove the igraph "feature"...  Or remove groups.py from the repo....

**Comment by aphearin** [comment]
I don't want to remove groups.py, this looks great. 

Since there are two versions of igraph, we should probably make the igraph_available boolean written so that it knows how to distinguish between the two different packages. So for the short term, it just depends on how big of a pain figuring out that is relative to removing the igraph feature temporarily.

**Comment by duncandc** [comment]
I could just throw in a "try: import igraph.Graph"

**Comment by aphearin** [comment]
That's a fine (temporary) workaround.

**Comment by aphearin** [comment]
I uninstalled igraph, ran the test suite, and everything passes. Then I reinstalled python-igraph, re-ran the test suite, and everything passes. So everything is entirely kosher. It's just that annoying problem of there being two versions of igraph floating around. 

Let's just put this on the back-burner for now. At some point, we should decide on whether igraph should be added as a dependency.
