### ISSUE TITLE
py.test and cython

### ISSUE THREAD

**Issue by aphearin** [astropy/halotools#97]
@eteq - I know you have been consulting with @duncandc over the past couple of weeks about cythonization. There is some new and strange phenomenology that I'm wondering if you've encountered before. This may be more efficient to discuss in person, I don't know. But in the current version of master (which has a test failure - see #96 ), I'm no longer able to test specific modules. I can run the entire test suite at once, but if I try "python setup.py test -t fname", I get the following error:

error: [Errno 2] Could not find C file halotools/mock_observables/pair_counters/cpairs/cpairs.c for Cython file halotools/mock_observables/pair_counters/cpairs/cpairs.pyx when building extension halotools.mock_observables.pair_counters.cpairs.cpairs. Cython must be installed to build from a git checkout.: 'halotools/mock_observables/pair_counters/cpairs/cpairs.c'

I strongly suspect this is related to conventions we have discussed previously in #69 .

**Comment by aphearin** [comment]
Actually, the problem has nothing to do with testing a single module. The problem is that the test suite cannot be run twice in a row without a fatal error. It looks like the code is built during the first test execution, and then for some reason during the second execution the code cannot detect the previously compiled code.

**Comment by aphearin** [comment]
@duncandc - would you mind just running the test suite twice in succession confirm whether this behavior happens on an independent machine?

**Comment by duncandc** [comment]
I can confirm this behavior.  I think the presence of the .c and/or .cpp files confuses it...

**Comment by aphearin** [comment]
Ok, thanks for confirming. I may have to monkey around with the mock_observables setup files to get this to work. I'll keep you abreast of progress.
